/*
 * @input file  NIU R1 CAN 协议.xlsx
 * @output file niu_export_enum.h
 * @ver   版本号
 * @time   2018-12-27 15:32:45
 * @code Author:刘振
 * @tool Author:冯龙
 * @brief  设备PGN清单，设备数据读写用的参数ID等
 */


#ifndef __NIU_EXPORT_ENUM_H_
#define __NIU_EXPORT_ENUM_H_

#ifdef __cplusplus
 extern "C" {
#endif


typedef enum _niu_device_type_
{
	NIU_ECU = 1,       // 中控		
	NIU_LCU,
	NIU_NBC,
	NIU_LKU,
	NIU_VCU,
	NIU_DB,  
	NIU_FOC,      
	NIU_BMS,      
	NIU_BMS2,     
	NIU_MAX,
	NIU_ALL=0xff,

}NIU_DATA_ADDR_BASE;


typedef enum _niu_data_type
{
	NIU_INT8 = 0,
	NIU_UINT8,
	NIU_INT16,
	NIU_UINT16,
	NIU_INT32,
	NIU_UINT32,
	NIU_STRING,
	NIU_ARRAY,
	NIU_FLOAT,
	NIU_DOUBLE,
	NIU_NULL = 0xFF
}NIU_DATA_TYPE;





// 由 ECU_PGN 数据表生成
// ECU PGN清单

typedef enum _niu_pgn_ecu_list
{
    
	PGN_ECU_BOOT_SOFT_VERSION = 61696, // BOOT软件版本
	PGN_ECU_BOOT_COMPILE_TIME = 61697, // BOOT编译时间
	PGN_ECU_APP_SOFT_VERSION = 61700, // APP软件版本
	PGN_ECU_APP_COMPILE_TIME = 61701, // APP编译时间
	PGN_ECU_HARD_VERSION = 61704, // 硬件版本号
	PGN_ECU_SERIAL_NUMBER = 61705, // 生产序列号
	PGN_ECU_GLOBAL_STATE = 61707, // 设备全局状态
	PGN_ECU_TIMESTAMP = 61707, // 时间戳
	PGN_ECU_WRITE_KEY_LEVER = 61708, // 写参数密码
	PGN_ECU_BUS_KEY = 61708, // 总线通讯秘钥
	PGN_ECU_BASICS_CMD = 61709, // 基础命令码
	PGN_ECU_AUTH_RAND1 = 61709, // RAND1
	PGN_ECU_RESERVE_1 = 61710, // RESERVE
	PGN_ECU_AUTH_RAND2 = 61710, // RAND2
	PGN_ECU_AUTH_ANS1 = 61711, // ANS1
	PGN_ECU_AUTH_RAND3 = 61711, // RAND3
	PGN_ECU_AUTH_ANS2 = 61712, // ANS2
	PGN_ECU_AUTH_RESULT = 61712, // 鉴权结果
	PGN_ECU_AUTH_FAULT_CNT = 61713, // 鉴权错误次数
	PGN_ECU_BASICS_STATUES = 61713, // 基础设备状态
	PGN_ECU_BASICS_ERR_STATUS = 61714, // 基础故障状态
	PGN_ECU_MCU_TEMP = 61714, // 设备温度
	PGN_ECU_RESERVE_2 = 61715, // RESERVE
	PGN_ECU_DEALER_CODE = 61715, // 经销商编码
	PGN_ECU_UTC = 61716, // 时区
	PGN_ECU_MOVED_LENGTH = 61716, // 异动判断距离
	PGN_ECU_CAR_TYPE = 61716, // 车型编号
	PGN_ECU_FAIL_VALUE = 61717, // 倾倒检测阈值
	PGN_ECU_MOVE_GSENSOR_COUNT = 61717, // 检测到震动次数
	PGN_ECU_MOVE_GSENSOR_TIME = 61717, // 检测时间
	PGN_ECU_CAR_SPEED_INDEX = 61717, // 仪表速度系数
	PGN_ECU_TIZE_SIZE = 61718, // 轮胎周长
	PGN_ECU_LOST_ENERY = 61718, // 当日消耗电量wh
	PGN_ECU_LOST_SOC = 61719, // 当日消耗电量
	PGN_ECU_LAST_MILEAGE = 61719, // 上次骑行里程
	PGN_ECU_TOTAL_MILEAGE = 61720, // 总行驶里程
	PGN_ECU_SPEED_LOC_SOC = 61720, // 低电量限速开始电量
	PGN_ECU_CHARGE_VALUE = 61720, // 充电开启电压
	PGN_ECU_DISCHARGE_VALUE = 61720, // 结束充电电压
	PGN_ECU_SHAKING_VALUE = 61720, // 震动检测阀值
	PGN_ECU_OTA_BIN_URL = 61721, // 固件URL
	PGN_ECU_OTA_SOFT_VER = 61729, // 固件升级软件版本
	PGN_ECU_OTA_HARD_VER = 61730, // 固件升级硬件版本
	PGN_ECU_OTA_PACK_SIZE = 61731, // 固件大小
	PGN_ECU_OTA_RATE = 61731, // 固件升级设备进度
	PGN_ECU_OTA_EXEC_EQP = 61732, // 固件升级设备
	PGN_ECU_OTA_EQP = 61732, // 要升级的设备
	PGN_ECU_DB_CODE_DIS_TIME = 61732, // 仪表随机码显示时间
	PGN_ECU_DISPLAY_RANDOM_CODE = 61732, // 仪表显示随机码
	PGN_ECU_APP_CONTROL = 61733, // 服务器控制字段
	PGN_ECU_LIMITING_VELOCITY_MAX = 61733, // 进入双限速转速
	PGN_ECU_LIMITING_VELOCITY_MIN = 61734, // 退出双限速转速
	PGN_ECU_FRONT_TIRE_SIZE = 61734, // 前轮周长
	PGN_ECU_BLE_MAC = 61735, // 蓝牙mac地址
	PGN_ECU_BLE_PASSWORD = 61736, // 蓝牙密码
	PGN_ECU_BLE_AES = 61738, // 蓝牙秘钥
	PGN_ECU_BLE_NAME = 61740, // 蓝牙名称
	PGN_ECU_SERVER_URL = 61744, // 服务器域名
	PGN_ECU_SERVER_URL2 = 61748, // IOT备用服务器域名
	PGN_ECU_SERVER_ERROR_URL = 61752, // err上报服务器域名
	PGN_ECU_SERVER_ERROR_URL2 = 61756, // err上报备用服务器域名
	PGN_ECU_SERVER_LBS_URL = 61760, // LBS服务器域名
	PGN_ECU_SERVER_LBS_URL2 = 61764, // LBS备用服务器域名
	PGN_ECU_SERVER_PORT = 61768, // 服务器端口
	PGN_ECU_SERVER_PORT2 = 61768, // IOT备用服务器端口
	PGN_ECU_SERVER_ERROR_PORT = 61769, // err上报服务器端口
	PGN_ECU_SERVER_ERROR_PORT2 = 61769, // err上报备用服务器端口
	PGN_ECU_SERVER_LBS_PORT = 61770, // LBS服务器端口
	PGN_ECU_SERVER_LBS_PORT2 = 61770, // LBS备用服务器端口
	PGN_ECU_ECU_KEEPALIVE = 61771, // 心跳包间隔
	PGN_ECU_RESERVE_3 = 61771, // RESERVE
	PGN_ECU_IMEI = 61772, // IMEI
	PGN_ECU_ICCID = 61774, // ICCID
	PGN_ECU_IMSI = 61777, // IMSI
	PGN_ECU_NO_CDMA_LOCATION = 61779, // 非cdma时基站信息
	PGN_ECU_CDMA_LOCATION = 61787, // cdma时基站信息
	PGN_ECU_LONGITUDE = 61795, // 经度
	PGN_ECU_LATITUDE = 61796, // 纬度
	PGN_ECU_AVG_LONGITUDE = 61797, // 驻车GPS平均经度
	PGN_ECU_AVG_LATITUDE = 61798, // 驻车GPS平均纬度
	PGN_ECU_IP = 61799, // 入网IP
	PGN_ECU_HDOP = 61799, // 定位精度
	PGN_ECU_PHOP = 61800, // 定位精度
	PGN_ECU_HEADING = 61800, // 航向
	PGN_ECU_GPS_SPEED = 61801, // GPS速度速度
	PGN_ECU_GPS_MAX_CNR = 61801, // 最大GPS信号强度
	PGN_ECU_GPS_MIN_CNR = 61802, // 最小GPS信号强度
	PGN_ECU_GPS_AVG_CNR = 61802, // 平均GPS信号强度
	PGN_ECU_GPS_SEILL_NUM = 61803, // 定位卫星数量
	PGN_ECU_GPS_SLEEP_TIME = 61803, // 驻车gps休眠间隔
	PGN_ECU_GPS_AWAKE_TIME = 61804, // 驻车gps唤醒时长
	PGN_ECU_PITCH = 61804, // 俯仰角
	PGN_ECU_ROLL = 61805, // 翻滚角
	PGN_ECU_YAW = 61805, // 俯仰角
	PGN_ECU_X_ACC = 61806, // X轴加速度
	PGN_ECU_Y_ACC = 61806, // Y轴加速度
	PGN_ECU_Z_ACC = 61806, // Z轴加速度
	PGN_ECU_X_ANG = 61806, // X轴角加速度
	PGN_ECU_Y_ANG = 61807, // Y轴角加速度
	PGN_ECU_Z_ANG = 61807, // Z轴角加速度
	
}NIU_PGN_ECU_LIST;



// 由 LCU_PGN 数据表生成
// LCU PGN清单

typedef enum _niu_pgn_lcu_list
{
    
	PGN_LCU_BOOT_SOFT_VERSION = 61952, // BOOT软件版本
	PGN_LCU_BOOT_COMPILE_TIME = 61953, // BOOT编译时间
	PGN_LCU_APP_SOFT_VERSION = 61956, // APP软件版本
	PGN_LCU_APP_COMPILE_TIME = 61957, // APP编译时间
	PGN_LCU_HARD_VERSION = 61960, // 硬件版本号
	PGN_LCU_SERIAL_NUMBER = 61961, // 生产序列号
	PGN_LCU_GLOBAL_STATE = 61963, // 设备全局状态
	PGN_LCU_TIMESTAMP = 61963, // 时间戳
	PGN_LCU_WRITE_KEY_LEVER = 61964, // 写参数密码
	PGN_LCU_BUS_KEY = 61964, // 总线通讯秘钥
	PGN_LCU_BASICS_CMD = 61965, // 基础命令码
	PGN_LCU_AUTH_RAND1 = 61965, // RAND1
	PGN_LCU_RESERVE_1 = 61966, // RESERVE
	PGN_LCU_AUTH_RAND2 = 61966, // RAND2
	PGN_LCU_AUTH_ANS1 = 61967, // ANS1
	PGN_LCU_AUTH_RAND3 = 61967, // RAND3
	PGN_LCU_AUTH_ANS2 = 61968, // ANS2
	PGN_LCU_AUTH_RESULT = 61968, // 鉴权结果
	PGN_LCU_AUTH_FAULT_CNT = 61969, // 鉴权错误次数
	PGN_LCU_BASICS_STATUES = 61969, // 基础设备状态
	PGN_LCU_BASICS_ERR_STATUS = 61970, // 基础故障状态
	PGN_LCU_MCU_TEMP = 61970, // 设备温度
	PGN_LCU_STATE = 61971, // 整机状态
	PGN_LCU_SWITCH_STATE = 61971, // 组合开关状态
	PGN_LCU_LIGHT_STATE = 61971, // 灯具状态
	PGN_LCU_X_ACC = 61972, // X轴加速度 
	PGN_LCU_Y_ACC = 61972, // Y轴加速度 
	PGN_LCU_Z_ACC = 61972, // Z轴加速度 
	PGN_LCU_X_ANG = 61972, // X轴角加速度
	PGN_LCU_Y_ANG = 61973, // Y轴角加速度
	PGN_LCU_Z_ANG = 61973, // Y轴角加速度
	PGN_LCU_CAR_STATE = 61973, // 车辆状态
	PGN_LCU_RESERVE_2 = 61973, // RESERVE
	PGN_LCU_LIGHT_FAULT = 61974, // 灯光故障
	
}NIU_PGN_LCU_LIST;



// 由 NBC_PGN 数据表生成
// NBC PGN清单

typedef enum _niu_pgn_nbc_list
{
    
	PGN_NBC_BOOT_SOFT_VERSION = 62208, // BOOT软件版本
	PGN_NBC_BOOT_COMPILE_TIME = 62209, // BOOT编译时间
	PGN_NBC_APP_SOFT_VERSION = 62212, // APP软件版本
	PGN_NBC_APP_COMPILE_TIME = 62213, // APP编译时间
	PGN_NBC_HARD_VERSION = 62216, // 硬件版本号
	PGN_NBC_SERIAL_NUMBER = 62217, // 生产序列号
	PGN_NBC_GLOBAL_STATE = 62219, // 设备全局状态
	PGN_NBC_TIMESTAMP = 62219, // 时间戳
	PGN_NBC_WRITE_KEY_LEVER = 62220, // 写参数密码
	PGN_NBC_BUS_KEY = 62220, // 总线通讯秘钥
	PGN_NBC_BASICS_CMD = 62221, // 基础命令码
	PGN_NBC_AUTH_RAND1 = 62221, // RAND1
	PGN_NBC_RESERVE_1 = 62222, // RESERVE
	PGN_NBC_AUTH_RAND2 = 62222, // RAND2
	PGN_NBC_AUTH_ANS1 = 62223, // ANS1
	PGN_NBC_AUTH_RAND3 = 62223, // RAND3
	PGN_NBC_AUTH_ANS2 = 62224, // ANS2
	PGN_NBC_AUTH_RESULT = 62224, // 鉴权结果
	PGN_NBC_AUTH_FAULT_CNT = 62225, // 鉴权错误次数
	PGN_NBC_BASICS_STATUES = 62225, // 基础设备状态
	PGN_NBC_BASICS_ERR_STATUS = 62226, // 基础故障状态
	PGN_NBC_MCU_TEMP = 62226, // 设备温度
	PGN_NBC_RESERVE_2 = 62227, // RESERVE
	PGN_NBC_LIFEVALUE = 62228, // 循环心跳
	PGN_NBC_WARNING = 62228, // 一级故障
	PGN_NBC_FAULT = 62228, // 二级故障
	PGN_NBC_POWER_STATE = 62228, // 电源工作状态
	PGN_NBC_SWITCHING_SIGNAL = 62228, // 开关信号
	PGN_NBC_FANS_PEED = 62229, // 风扇转速
	PGN_NBC_FANS_PEED_CONTROL = 62229, // 风扇转速控制
	PGN_NBC_LED_STATE = 62229, // LED状态
	PGN_NBC_BATTERY_TYPE = 62229, // 充电器接入识别
	PGN_NBC_MAIN_VOLTAGE1 = 62230, // 输出电压1
	PGN_NBC_MAIN_VOLTAGE2 = 62230, // 输出电压2
	PGN_NBC_MAIN_CURRENT = 62230, // 输出电流
	PGN_NBC_12V_VOLTAGE = 62230, // 12V电压
	PGN_NBC_MAIN_TEMPERATURE = 62231, // 温度
	PGN_NBC_REFERENCE_VOLTAGE = 62231, // 参考电压
	PGN_NBC_CHARGE_OVP = 62231, // 充电保护电压
	PGN_NBC_CHARGE_OCP = 62231, // 充电保护电流
	PGN_NBC_MAIN_VOLTAGE1_ADC = 62232, // 输出电压1AD
	PGN_NBC_MAIN_VOLTAGE2_ADC = 62232, // 输出电压2AD
	PGN_NBC_MAIN_CURRENT_ADC = 62232, // 输出电流AD
	PGN_NBC_12V_VOLTAGE_ADC = 62232, // 12V电源AD
	PGN_NBC_MAIN_VOLTAGE_CONTROL_ADC = 62233, // 电压控制AD
	PGN_NBC_MAIN_CURRENT_CONTROL_ADC = 62233, // 电流控制AD
	PGN_NBC_REFERENCE_TEMPERATURE_ADC = 62233, // 参考电压AD
	PGN_NBC_MAIN_TEMPERATURE_ADC = 62233, // 温度采集AD
	PGN_NBC_BATTERY_TYPE_ADC = 62234, // 充电接入信号AD
	PGN_NBC_RESERVE_3 = 62234, // 预留
	PGN_NBC_CHARGE_VOLTAGE_NEED = 62235, // 充电需求电压
	PGN_NBC_CHARGE_CURRENT_NEED = 62235, // 充电需求电流
	PGN_NBC_CHARGE_MODE_NEED = 62235, // 充电需求模式
	PGN_NBC_RESERVE_4 = 62235, // 预留
	PGN_NBC_FANS_CONTROL_FREQUENCY = 62236, // 风扇控制信号频率
	PGN_NBC_FANS_PEED_MAX = 62236, // 风扇最大速度
	PGN_NBC_RESERVE_5 = 62236, // 预留
	PGN_NBC_MAIN_TEMPERATURE_WARNING = 62237, // 高温警告值
	PGN_NBC_MAIN_TEMPERATURE_WARNING_RECOVER = 62237, // 高温警告撤销值
	PGN_NBC_MAIN_TEMPERATURE_FAULT = 62237, // 高温故障保护值
	PGN_NBC_MAIN_TEMPERATURE_FAULT_RECOVER = 62237, // 高温故障撤销值
	PGN_NBC_MAIN_OVP = 62238, // 电源输出过压保护
	PGN_NBC_MAIN_OCP = 62238, // 电源输出过流保护
	PGN_NBC_MAIN_LVP = 62238, // 电源输出低压保护
	PGN_NBC_RESERVE_6 = 62238, // 预留
	PGN_NBC_MAIN_VOLTAGE_CONTROL_SIGNAL_RATIO = 62239, // 电压控制基准比例
	PGN_NBC_MAIN_VOLTAGE_CONTROL_SIGNAL_P = 62239, // 电压基准控制P
	PGN_NBC_MAIN_VOLTAGE_CONTROL_SIGNAL_I = 62239, // 电压基准控制I
	PGN_NBC_MAIN_VOLTAGE_CONTROL_SIGNAL_D = 62239, // 电压基准控制D
	PGN_NBC_MAIN_VOLTAGE_CONTROL_P = 62240, // 电压控制P
	PGN_NBC_MAIN_VOLTAGE_CONTROL_I = 62240, // 电压控制I
	PGN_NBC_MAIN_VOLTAGE_CONTROL_D = 62240, // 电压控制D
	PGN_NBC_RESERVE_7 = 62240, // 预留
	PGN_NBC_MAIN_CURRENT_CONTROL_SIGNAL_RATIO = 62241, // 电流控制基准比例
	PGN_NBC_MAIN_CURRENT_CONTROL_SIGNAL_P = 62241, // 电流基准控制P
	PGN_NBC_MAIN_CURRENT_CONTROL_SIGNAL_I = 62241, // 电流基准控制I
	PGN_NBC_MAIN_CURRENT_CONTROL_SIGNAL_D = 62241, // 电流基准控制D
	PGN_NBC_MAIN_CURRENT_CONTROL_P = 62242, // 电流控制P
	PGN_NBC_MAIN_CURRENT_CONTROL_I = 62242, // 电流控制I
	PGN_NBC_MAIN_CURRENT_CONTROL_D = 62242, // 电流控制D
	PGN_NBC_RESERVE_8 = 62242, // 预留
	PGN_NBC_MAIN_VOLTAGE1_SIGNAL_RATIO = 62243, // 输出电压1计算比例
	PGN_NBC_MAIN_VOLTAGE2_SIGNAL_RATIO = 62243, // 输出电压2计算比例
	PGN_NBC_MAIN_CURRENT_SIGNAL_RATIO = 62243, // 输出电流计算比例
	PGN_NBC_12V_VOLTAGE_SIGNAL_RATIO = 62243, // 12V电源计算比例
	PGN_NBC_CHARGE_OVP_DEVIANT = 62244, // 充电过压保护偏移值
	PGN_NBC_CHARGE_OVP_RECOVER_DEVIANT = 62244, // 充电过压恢复偏移值
	PGN_NBC_CHARGE_OCP_DEVIANT = 62244, // 充电过流保护偏移值
	PGN_NBC_CHARGE_OCP_RECOVER_DEVIANT = 62244, // 充电过流恢复偏移值
	PGN_NBC_CHARGE_LVP_DEVIANT = 62245, // 充电低压保护偏移值
	PGN_NBC_CHARGE_LVP_RECOVER_DEVIANT = 62245, // 充电低压恢复偏移值
	PGN_NBC_RESERVE_9 = 62245, // 预留
	PGN_NBC_CHARGE_DROPOUT_VOLTAGE_WARNING_DEVIANT = 62246, // 充电单节压差警告偏移值
	PGN_NBC_CHARGE_DROPOUT_VOLTAGE_WARNING_RECOVER_DEVIANT = 62246, // 充电单节压差警告撤销偏移值
	PGN_NBC_CHARGE_DROPOUT_VOLTAGE_FAULT_DEVIANT = 62246, // 充电单节压差保护偏移值
	PGN_NBC_CHARGE_DROPOUT_VOLTAGE_FAULT_RECOVER_DEVIANT = 62246, // 充电单节压差保护撤销偏移值
	PGN_NBC_CHARGE_TEMPERATURE_LOW_WARNING_DEVIANT = 62247, // 充电电池低温警告偏移值
	PGN_NBC_CHARGE_TEMPERATURE_LOW_WARNING_RECOVER_DEVIANT = 62247, // 充电电池低温警告撤销偏移值
	PGN_NBC_CHARGE_TEMPERATURE_LOW_FAULT_DEVIANT = 62247, // 充电电池低温保护偏移值
	PGN_NBC_CHARGE_TEMPERATURE_LOW_FAULT_RECOVER_DEVIANT = 62247, // 充电电池低温保护撤销偏移值
	PGN_NBC_CHARGE_TEMPERATURE_OVER_WARNING_DEVIANT = 62248, // 充电电池高温警告偏移值
	PGN_NBC_CHARGE_TEMPERATURE_OVER_WARNING_RECOVER_DEVIANT = 62248, // 充电电池高温警告撤销偏移值
	PGN_NBC_CHARGE_TEMPERATURE_OVER_FAULT_DEVIANT = 62248, // 充电电池高温保护偏移值
	PGN_NBC_CHARGE_TEMPERATURE_OVER_FAULT_RECOVER_DEVIANT = 62248, // 充电电池高温保护撤销偏移值
	
}NIU_PGN_NBC_LIST;



// 由 LKU_PGN 数据表生成
// LKU PGN清单

typedef enum _niu_pgn_lku_list
{
    
	PGN_LKU_BOOT_SOFT_VERSION = 62464, // BOOT软件版本
	PGN_LKU_BOOT_COMPILE_TIME = 62465, // BOOT编译时间
	PGN_LKU_APP_SOFT_VERSION = 62468, // APP软件版本
	PGN_LKU_APP_COMPILE_TIME = 62469, // APP编译时间
	PGN_LKU_HARD_VERSION = 62472, // 硬件版本号
	PGN_LKU_SERIAL_NUMBER = 62473, // 生产序列号
	PGN_LKU_GLOBAL_STATE = 62475, // 设备全局状态
	PGN_LKU_TIMESTAMP = 62475, // 时间戳
	PGN_LKU_WRITE_KEY_LEVER = 62476, // 写参数密码
	PGN_LKU_BUS_KEY = 62476, // 总线通讯秘钥
	PGN_LKU_BASICS_CMD = 62477, // 基础命令码
	PGN_LKU_AUTH_RAND1 = 62477, // RAND1
	PGN_LKU_RESERVE_1 = 62478, // RESERVE
	PGN_LKU_AUTH_RAND2 = 62478, // RAND2
	PGN_LKU_AUTH_ANS1 = 62479, // ANS1
	PGN_LKU_AUTH_RAND3 = 62479, // RAND3
	PGN_LKU_AUTH_ANS2 = 62480, // ANS2
	PGN_LKU_AUTH_RESULT = 62480, // 鉴权结果
	PGN_LKU_AUTH_FAULT_CNT = 62481, // 鉴权错误次数
	PGN_LKU_BASICS_STATUES = 62481, // 基础设备状态
	PGN_LKU_BASICS_ERR_STATUS = 62482, // 基础故障状态
	PGN_LKU_MCU_TEMP = 62482, // 设备温度
	PGN_LKU_RESERVE_2 = 62483, // RESERVE
	PGN_LKU_CFG = 62483, // 配置表
	PGN_LKU_STATUS = 62484, // 锁控状态
	PGN_LKU_ALARM_STATE = 62484, // 报警器状态
	PGN_LKU_LOCK1_STATE = 62484, // 坐垫锁状态
	PGN_LKU_LOCK2_STATE = 62484, // 尾箱锁状态
	PGN_LKU_LOCK3_STATE = 62484, // 龙头锁状态
	PGN_LKU_HELMET_STATE = 62484, // 头盔状态
	PGN_LKU_ALARM_CMD = 62485, // 报警器命令
	PGN_LKU_SADDLE_CMD = 62485, // 坐垫锁命令
	PGN_LKU_TAIL_BOX_CMD = 62485, // 尾箱锁命令
	PGN_LKU_HEAD_KLOCK_CMD = 62485, // 龙头锁命令
	PGN_LKU_BATTERY_SOC = 62485, // 内电池电量
	PGN_LKU_SADDLE_CUR = 62485, // 最后一次坐垫锁电流
	PGN_LKU_TAIL_BOX_CUR = 62485, // 最后一次尾箱锁电流
	PGN_LKU_HEAD_LOCK_CUR = 62486, // 最后一次龙头锁电流
	PGN_LKU_VLOCK_STA = 62486, // 最后一次锁供电电压
	PGN_LKU_VIN_STATUS = 62486, // 外电电压
	PGN_LKU_VLOCK_STATUS = 62486, // 锁供电电压
	PGN_LKU_VBAT_STATUS = 62487, // 内电电压
	PGN_LKU_VDD_STATUS = 62487, // MCU供电电压
	PGN_LKU_SADDLE_TIMEOUT = 62487, // 坐垫锁开解锁超时时间
	PGN_LKU_TAIL_BOX_TIMEOUT = 62487, // 尾箱锁开解锁超时时间
	PGN_LKU_HEAD_LOCK_TIMEOUT = 62488, // 龙头锁开解锁超时时间
	
}NIU_PGN_LKU_LIST;



// 由 VCU_PGN 数据表生成
// VCU PGN清单

typedef enum _niu_pgn_vcu_list
{
    
	PGN_VCU_BOOT_SOFT_VERSION = 62720, // BOOT软件版本
	PGN_VCU_BOOT_COMPILE_TIME = 62721, // BOOT编译时间
	PGN_VCU_APP_SOFT_VERSION = 62724, // APP软件版本
	PGN_VCU_APP_COMPILE_TIME = 62725, // APP编译时间
	PGN_VCU_HARD_VERSION = 62728, // 硬件版本号
	PGN_VCU_SERIAL_NUMBER = 62729, // 生产序列号
	PGN_VCU_GLOBAL_STATE = 62731, // 设备全局状态
	PGN_VCU_TIMESTAMP = 62731, // 时间戳
	PGN_VCU_WRITE_KEY_LEVER = 62732, // 写参数密码
	PGN_VCU_BUS_KEY = 62732, // 总线通讯秘钥
	PGN_VCU_BASICS_CMD = 62733, // 基础命令码
	PGN_VCU_AUTH_RAND1 = 62733, // RAND1
	PGN_VCU_RESERVE_1 = 62734, // RESERVE
	PGN_VCU_AUTH_RAND2 = 62734, // RAND2
	PGN_VCU_AUTH_ANS1 = 62735, // ANS1
	PGN_VCU_AUTH_RAND3 = 62735, // RAND3
	PGN_VCU_AUTH_ANS2 = 62736, // ANS2
	PGN_VCU_AUTH_RESULT = 62736, // 鉴权结果
	PGN_VCU_AUTH_FAULT_CNT = 62737, // 鉴权错误次数
	PGN_VCU_BASICS_STATUES = 62737, // 基础设备状态
	PGN_VCU_BASICS_ERR_STATUS = 62738, // 基础故障状态
	PGN_VCU_MCU_TEMP = 62738, // 设备温度
	PGN_VCU_RESERVE_2 = 62739, // RESERVE
	PGN_VCU_TEMP = 62739, // 当前温度值
	PGN_START_KEY_STATUS = 62740, // 一键启动状态 
	PGN_VCU_SHAKE_ALARM_STATUS = 62740, // 震动报警值
	PGN_VCU_DISC_POWER = 62741, // 放电功率
	PGN_VCU_C_POWER = 62741, // 充电功率
	PGN_VCU_PUMP_STATE = 62742, // 水泵控制状态
	PGN_VCU_EBS_CONT = 62742, // EBS控制位
	PGN_VCU_DCDC_CONT = 62742, // DCDC控制位
	PGN_VCU_MOVE_GSENSOR_COUNT = 62742, // 检测到震动次数
	PGN_VCU_PITCH = 62742, // 倾斜角度值
	PGN_VCU_ROLL = 62743, // 翻滚角度值
	PGN_VCU_YAW = 62743, // 仰俯角度值
	PGN_VCU_RF_ID1 = 62744, // 遥控器ID1
	PGN_VCU_RF_ID2 = 62744, // 遥控器ID2
	PGN_VCU_RF_ID3 = 62745, // 遥控器ID3
	PGN_VCU_RF_ID4 = 62745, // 遥控器ID4
	PGN_VCU_LITTLE_BAT_VAL = 62746, // 小电池电压
	PGN_VCU_LITTLE_BAT_STATUS = 62746, // 小电池状态
	PGN_VCU_GEAR_VALUE = 62746, // 档位值
	PGN_VCU_LIMIT_VELOCITY = 62746, // 限速状态
	
}NIU_PGN_VCU_LIST;



// 由 DB_PGN 数据表生成
// DB PGN清单

typedef enum _niu_pgn_db_list
{
    
	PGN_DB_BOOT_SOFT_VERSION = 62976, // BOOT软件版本
	PGN_DB_BOOT_COMPILE_TIME = 62977, // BOOT编译时间
	PGN_DB_APP_SOFT_VERSION = 62980, // APP软件版本
	PGN_DB_APP_COMPILE_TIME = 62981, // APP编译时间
	PGN_DB_HARD_VERSION = 62984, // 硬件版本号
	PGN_DB_SERIAL_NUMBER = 62985, // 生产序列号
	PGN_DB_GLOBAL_STATE = 62987, // 设备全局状态
	PGN_DB_TIMESTAMP = 62987, // 时间戳
	PGN_DB_WRITE_KEY_LEVER = 62988, // 写参数密码
	PGN_DB_BUS_KEY = 62988, // 总线通讯秘钥
	PGN_DB_BASICS_CMD = 62989, // 基础命令码
	PGN_DB_AUTH_RAND1 = 62989, // RAND1
	PGN_DB_RESERVE_1 = 62990, // RESERVE
	PGN_DB_AUTH_RAND2 = 62990, // RAND2
	PGN_DB_AUTH_ANS1 = 62991, // ANS1
	PGN_DB_AUTH_RAND3 = 62991, // RAND3
	PGN_DB_AUTH_ANS2 = 62992, // ANS2
	PGN_DB_AUTH_RESULT = 62992, // 鉴权结果
	PGN_DB_AUTH_FAULT_CNT = 62993, // 鉴权错误次数
	PGN_DB_BASICS_STATUES = 62993, // 基础设备状态
	PGN_DB_BASICS_ERR_STATUS = 62994, // 基础故障状态
	PGN_DB_MCU_TEMP = 62994, // 设备温度
	PGN_DB_RESERVE_2 = 62995, // RESERVE
	PGN_DB_STATUS = 62995, // 机车状态
	PGN_DB_GEARS = 62995, // 档位
	PGN_DB_SPEED = 62995, // 速度
	PGN_DB_C_CUR = 62996, // 充电电流
	PGN_DB_DC_CUR = 62996, // 放电电流
	PGN_DB_BAT_SOC = 62996, // 电池SOC
	PGN_DB_FULL_C_T = 62996, // 充电剩余时间
	PGN_DB_HOUR = 62996, // 当前小时
	PGN_DB_MIN = 62996, // 当前分钟
	PGN_DB_F_CODE = 62996, // 故障代码
	PGN_DB_BAT2_SOC = 62996, // 电池2SOC
	PGN_DB_TOTAL_SOC = 62997, // 总电池SOC
	PGN_DB_RGB_SET = 62997, // RGB指令
	PGN_DB_STATUS2 = 62998, // 车辆状态2
	PGN_DB_RGB_CONFIG = 62998, // RGB配色命令
	PGN_DB_MILEAGE = 62999, // 里程数
	
}NIU_PGN_DB_LIST;



// 由 FOC_PGN 数据表生成
// FOC PGN清单

typedef enum _niu_pgn_foc_list
{
    
	PGN_FOC_BOOT_SOFT_VERSION = 63232, // BOOT软件版本
	PGN_FOC_BOOT_COMPILE_TIME = 63233, // BOOT编译时间
	PGN_FOC_APP_SOFT_VERSION = 63236, // APP软件版本
	PGN_FOC_APP_COMPILE_TIME = 63237, // APP编译时间
	PGN_FOC_HARD_VERSION = 63240, // 硬件版本号
	PGN_FOC_SERIAL_NUMBER = 63241, // 生产序列号
	PGN_FOC_GLOBAL_STATE = 63243, // 设备全局状态
	PGN_FOC_TIMESTAMP = 63243, // 时间戳
	PGN_FOC_WRITE_KEY_LEVER = 63244, // 写参数密码
	PGN_FOC_BUS_KEY = 63244, // 总线通讯秘钥
	PGN_FOC_BASICS_CMD = 63245, // 基础命令码
	PGN_FOC_AUTH_RAND1 = 63245, // RAND1
	PGN_FOC_RESERVE_1 = 63246, // RESERVE
	PGN_FOC_AUTH_RAND2 = 63246, // RAND2
	PGN_FOC_AUTH_ANS1 = 63247, // ANS1
	PGN_FOC_AUTH_RAND3 = 63247, // RAND3
	PGN_FOC_AUTH_ANS2 = 63248, // ANS2
	PGN_FOC_AUTH_RESULT = 63248, // 鉴权结果
	PGN_FOC_AUTH_FAULT_CNT = 63249, // 鉴权错误次数
	PGN_FOC_BASICS_STATUES = 63249, // 基础设备状态
	PGN_FOC_BASICS_ERR_STATUS = 63250, // 基础故障状态
	PGN_FOC_MCU_TEMP = 63250, // 设备温度
	PGN_FOC_RESERVE_2 = 63251, // RESERVE
	PGN_FOC_RATED_VLT = 63251, // 额定电压
	PGN_FOC_MIN_VLT = 63251, // 最低电压
	PGN_FOC_MAX_VLT = 63251, // 最高电压
	PGN_FOC_GEARS = 63251, // 档位
	PGN_FOC_RATED_CUR = 63252, // 额定电流
	PGN_FOC_MOTOR_SPEED = 63252, // 电机转速
	PGN_FOC_BAR_VLT = 63252, // 母线电压
	PGN_FOC_BAR_CUR = 63253, // 母线电流
	PGN_FOC_PHASE_CUR = 63253, // 当前相电流
	PGN_FOC_TORQUE = 63254, // 电机转矩
	PGN_FOC_MOTOR_TEMPERATURE = 63254, // 电机温度
	PGN_FOC_COTLSTA = 63254, // FOC状态
	PGN_FOC_THROTTLE_SENSOR = 63255, // 油门信号
	PGN_FOC_MATCHING_MOTOR_TYTP = 63255, // 匹配电机类型
	PGN_FOC_MATCHING_SPEED_SENSOR_TYTP = 63255, // 速度传感器类型
	PGN_FOC_SPEED_SENSOR_ANGLE = 63255, // 速度传感器相位角
	PGN_FOC_MOTOR_POLE_OF_PAIRS = 63255, // 电机及对数
	PGN_FOC_GEARBOX_REDUCTION_RATIO = 63255, // 变速箱减速比
	PGN_FOC_MAX_PHASE_CUR = 63255, // 最大相电流
	PGN_FOC_MIN_PHASE_CUR = 63256, // 最小相电流
	PGN_FOC_AVG_PHASE_CUR = 63256, // 平均电流
	PGN_FOC_SET_MAX_BAR_CUR = 63256, // 最大母线电流
	PGN_FOC_SET_MAX_ACCELERATING_TORQUE = 63256, // 设置加速最大转矩
	PGN_FOC_SET_MAX_RETARDING_TORQUE = 63257, // 设置减速最大转矩
	PGN_FOC_FOC_ACCELE = 63257, // 加速度
	PGN_FOC_FOC_DCCELE = 63257, // 减速度
	PGN_FOC_THROTTLE_MODE_SET = 63257, // 油门模式选择
	PGN_FOC_EBS_EN = 63258, // EBS使能
	PGN_FOC_EBS_RE_VLT = 63258, // EBS反充电压
	PGN_FOC_EBS_RE_CUR = 63258, // EBS反充电流
	PGN_FOC_BAT_SOFT_UV_EN = 63258, // 电池软欠压保护使能
	PGN_FOC_BAT_SOFT_UV_VLT = 63258, // 电池软欠压电压
	PGN_FOC_MOTER_RATED_SPEED = 63258, // 电机额定转速
	PGN_FOC_HIGH_SPEED_RATIO = 63259, // 高档位速度比例
	PGN_FOC_MID_SPEED_RATIO = 63259, // 中档位速度比例
	PGN_FOC_LOW_SPEED_RATIO = 63259, // 低档位速度比例
	PGN_FOC_HIGH_GER_CUR_LIMT_RATIO = 63259, // 高档位限流比例
	PGN_FOC_MID_GER_CUR_LIMT_RATIO = 63259, // 中档位限流比例
	PGN_FOC_LOW_GER_CUR_LIMT_RATIO = 63259, // 低档位限流比例
	PGN_FOC_FLUX_WEAKEN_EN = 63260, // 弱磁使能
	PGN_FOC_ENTER_FLUX_SPEED_RATIO = 63260, // 弱磁进入速度比例
	PGN_FOC_EXIT_FLUX_SPEED_RATIO = 63260, // 弱磁退出速度比例
	PGN_FOC_ENTER_FLUX_THROTTLE_VLT = 63260, // 弱磁进入油门电压
	PGN_FOC_FLUX_W_MAX_CUR = 63260, // 弱磁最大电流
	PGN_FOC_BOOST_EN = 63260, // Boost使能
	PGN_FOC_BOOST_MODE = 63260, // Boost模式
	PGN_FOC_BOOST_CUR = 63261, // Boost电流
	PGN_FOC_BOOST_KEEP_TIME = 63261, // Boost保持时间
	PGN_FOC_BOOST_INTERVAL_TIME = 63261, // Boost间隔时间
	PGN_FOC_START_AUTO_EN = 63261, // 暴起模式使能
	PGN_FOC_START_GEAR = 63261, // 暴起档位
	PGN_FOC_START_KEEP_TIME = 63261, // 暴起持续时间
	
}NIU_PGN_FOC_LIST;



// 由 BMS_PGN 数据表生成
// BMS PGN清单

typedef enum _niu_pgn_bms_list
{
    
	PGN_BMS_BOOT_SOFT_VERSION = 63488, // BOOT软件版本
	PGN_BMS_BOOT_COMPILE_TIME = 63489, // BOOT编译时间
	PGN_BMS_APP_SOFT_VERSION = 63492, // APP软件版本
	PGN_BMS_APP_COMPILE_TIME = 63493, // APP编译时间
	PGN_BMS_HARD_VERSION = 63496, // 硬件版本号
	PGN_BMS_SERIAL_NUMBER = 63497, // 生产序列号
	PGN_BMS_GLOBAL_STATE = 63499, // 设备全局状态
	PGN_BMS_TIMESTAMP = 63499, // 时间戳
	PGN_BMS_WRITE_KEY_LEVER = 63500, // 写参数密码
	PGN_BMS_BUS_KEY = 63500, // 总线通讯秘钥
	PGN_BMS_BASICS_CMD = 63501, // 基础命令码
	PGN_BMS_AUTH_RAND1 = 63501, // RAND1
	PGN_BMS_RESERVE_1 = 63502, // RESERVE
	PGN_BMS_AUTH_RAND2 = 63502, // RAND2
	PGN_BMS_AUTH_ANS1 = 63503, // ANS1
	PGN_BMS_AUTH_RAND3 = 63503, // RAND3
	PGN_BMS_AUTH_ANS2 = 63504, // ANS2
	PGN_BMS_AUTH_RESULT = 63504, // 鉴权结果
	PGN_BMS_AUTH_FAULT_CNT = 63505, // 鉴权错误次数
	PGN_BMS_BASICS_STATUES = 63505, // 基础设备状态
	PGN_BMS_BASICS_ERR_STATUS = 63506, // 基础故障状态
	PGN_BMS_MCU_TEMP = 63506, // 设备温度
	PGN_BMS_LIFEVALUE = 63507, // 心跳信号
	PGN_BMS_SOC = 63507, // SOC值
	PGN_BMS_SOH = 63507, // SOH值
	PGN_BMS_PACK_VOLTAGE = 63507, // 总电压
	PGN_BMS_CURRENT = 63507, // 电流值
	PGN_BMS_VOL_1 = 63508, // 电压1
	PGN_BMS_VOL_2 = 63508, // 电压2
	PGN_BMS_VOL_3 = 63508, // 电压3
	PGN_BMS_VOL_4 = 63508, // 电压4
	PGN_BMS_VOL_5 = 63509, // 电压5
	PGN_BMS_VOL_6 = 63509, // 电压6
	PGN_BMS_VOL_7 = 63509, // 电压7
	PGN_BMS_VOL_8 = 63509, // 电压8
	PGN_BMS_VOL_9 = 63510, // 电压9
	PGN_BMS_VOL_10 = 63510, // 电压10
	PGN_BMS_VOL_11 = 63510, // 电压11
	PGN_BMS_VOL_12 = 63510, // 电压12
	PGN_BMS_VOL_13 = 63511, // 电压13
	PGN_BMS_VOL_14 = 63511, // 电压14
	PGN_BMS_VOL_15 = 63511, // 电压15
	PGN_BMS_VOL_16 = 63511, // 电压16
	PGN_BMS_VOL_17 = 63512, // 电压17
	PGN_BMS_VOL_18 = 63512, // 电压18
	PGN_BMS_VOL_19 = 63512, // 电压19
	PGN_BMS_VOL_20 = 63512, // 电压20
	PGN_BMS_VOL_21 = 63513, // 电压21
	PGN_BMS_VOL_22 = 63513, // 电压22
	PGN_BMS_VOL_23 = 63513, // 电压23
	PGN_BMS_VOL_24 = 63513, // 电压24
	PGN_BMS_TEMP_1 = 63514, // 电芯温度1
	PGN_BMS_TEMP_2 = 63514, // 电芯温度2
	PGN_BMS_TEMP_3 = 63514, // 电芯温度3
	PGN_BMS_TEMP_4 = 63514, // 电芯温度4
	PGN_BMS_TEMP_5 = 63515, // 电芯温度5
	PGN_BMS_TEMP_6 = 63515, // 电芯温度6
	PGN_BMS_BALANCE_TEMP_1 = 63515, // 均衡温度1
	PGN_BMS_BALANCE_TEMP_2 = 63515, // 均衡温度2
	PGN_BMS_RECOVERY_MAX_POWER = 63516, // 最大允许回馈功率
	PGN_BMS_DISCHARGE_MAX_POWER = 63516, // 最大放电功率
	PGN_BMS_CHARGE_VOL = 63516, // 充电需求电压
	PGN_BMS_CHARGE_CUR = 63516, // 充电需求电流
	PGN_BMS_CYCLE_COUNT = 63517, // 已充电次数
	PGN_BMS_CHARGINGREMAINTIME  = 63517, // 充电剩余充电时间
	PGN_BMS_TAPY_CAPACITY = 63517, // 额定容量
	PGN_BMS_ACTUAL_CAPACITY = 63517, // 真实容量
	PGN_BMS_RELAY_STATUS = 63518, // 电继电器状态
	PGN_BMS_SYSTEM_STATUS = 63518, // 系统状态
	PGN_BMS_FLAUT_LEVEL = 63518, // 故障等级
	PGN_BMS_STATE = 63518, // 各通道均衡状态
	PGN_BMS_RESERVE_2 = 63518, // RESERVE
	PGN_BMS_FLAUT_STATUS = 63519, // 故障状态
	
}NIU_PGN_BMS_LIST;



// 由 BMS2_PGN 数据表生成
// BMS2 PGN清单

typedef enum _niu_pgn_bms2_list
{
    
	PGN_BMS2_BOOT_SOFT_VERSION = 63744, // BOOT软件版本
	PGN_BMS2_BOOT_COMPILE_TIME = 63745, // BOOT编译时间
	PGN_BMS2_APP_SOFT_VERSION = 63748, // APP软件版本
	PGN_BMS2_APP_COMPILE_TIME = 63749, // APP编译时间
	PGN_BMS2_HARD_VERSION = 63752, // 硬件版本号
	PGN_BMS2_SERIAL_NUMBER = 63753, // 生产序列号
	PGN_BMS2_GLOBAL_STATE = 63755, // 设备全局状态
	PGN_BMS2_TIMESTAMP = 63755, // 时间戳
	PGN_BMS2_WRITE_KEY_LEVER = 63756, // 写参数密码
	PGN_BMS2_BUS_KEY = 63756, // 总线通讯秘钥
	PGN_BMS2_BASICS_CMD = 63757, // 基础命令码
	PGN_BMS2_AUTH_RAND1 = 63757, // RAND1
	PGN_BMS2_RESERVE_1 = 63758, // RESERVE
	PGN_BMS2_AUTH_RAND2 = 63758, // RAND2
	PGN_BMS2_AUTH_ANS1 = 63759, // ANS1
	PGN_BMS2_AUTH_RAND3 = 63759, // RAND3
	PGN_BMS2_AUTH_ANS2 = 63760, // ANS2
	PGN_BMS2_AUTH_RESULT = 63760, // 鉴权结果
	PGN_BMS2_AUTH_FAULT_CNT = 63761, // 鉴权错误次数
	PGN_BMS2_BASICS_STATUES = 63761, // 基础设备状态
	PGN_BMS2_BASICS_ERR_STATUS = 63762, // 基础故障状态
	PGN_BMS2_MCU_TEMP = 63762, // 设备温度
	PGN_BMS2_LIFEVALUE = 63763, // 心跳信号
	PGN_BMS2_SOC = 63763, // SOC值
	PGN_BMS2_SOH = 63763, // SOH值
	PGN_BMS2_PACK_VOLTAGE = 63763, // 总电压
	PGN_BMS2_CURRENT = 63763, // 电流值
	PGN_BMS2_VOL_1 = 63764, // 电压1
	PGN_BMS2_VOL_2 = 63764, // 电压2
	PGN_BMS2_VOL_3 = 63764, // 电压3
	PGN_BMS2_VOL_4 = 63764, // 电压4
	PGN_BMS2_VOL_5 = 63765, // 电压5
	PGN_BMS2_VOL_6 = 63765, // 电压6
	PGN_BMS2_VOL_7 = 63765, // 电压7
	PGN_BMS2_VOL_8 = 63765, // 电压8
	PGN_BMS2_VOL_9 = 63766, // 电压9
	PGN_BMS2_VOL_10 = 63766, // 电压10
	PGN_BMS2_VOL_11 = 63766, // 电压11
	PGN_BMS2_VOL_12 = 63766, // 电压12
	PGN_BMS2_VOL_13 = 63767, // 电压13
	PGN_BMS2_VOL_14 = 63767, // 电压14
	PGN_BMS2_VOL_15 = 63767, // 电压15
	PGN_BMS2_VOL_16 = 63767, // 电压16
	PGN_BMS2_VOL_17 = 63768, // 电压17
	PGN_BMS2_VOL_18 = 63768, // 电压18
	PGN_BMS2_VOL_19 = 63768, // 电压19
	PGN_BMS2_VOL_20 = 63768, // 电压20
	PGN_BMS2_VOL_21 = 63769, // 电压21
	PGN_BMS2_VOL_22 = 63769, // 电压22
	PGN_BMS2_VOL_23 = 63769, // 电压23
	PGN_BMS2_VOL_24 = 63769, // 电压24
	PGN_BMS2_TEMP_1 = 63770, // 电芯温度1
	PGN_BMS2_TEMP_2 = 63770, // 电芯温度2
	PGN_BMS2_TEMP_3 = 63770, // 电芯温度3
	PGN_BMS2_TEMP_4 = 63770, // 电芯温度4
	PGN_BMS2_TEMP_5 = 63771, // 电芯温度5
	PGN_BMS2_TEMP_6 = 63771, // 电芯温度6
	PGN_BMS2_BALANCE_TEMP_1 = 63771, // 均衡温度1
	PGN_BMS2_BALANCE_TEMP_2 = 63771, // 均衡温度2
	PGN_BMS2_RECOVERY_MAX_POWER = 63772, // 最大允许回馈功率
	PGN_BMS2_DISCHARGE_MAX_POWER = 63772, // 最大放电功率
	PGN_BMS2_CHARGE_VOL = 63772, // 充电需求电压
	PGN_BMS2_CHARGE_CUR = 63772, // 充电需求电流
	PGN_BMS2_CYCLE_COUNT = 63773, // 已充电次数
	PGN_BMS2_CHARGING_REMAIN_TIME  = 63773, // 充电剩余充电时间
	PGN_BMS2_TAPY_CAPACITY = 63773, // 额定容量
	PGN_BMS2_ACTUAL_CAPACITY = 63773, // 真实容量
	PGN_BMS2_RELAY_STATUS = 63774, // 电继电器状态
	PGN_BMS2_SYSTEM_STATUS = 63774, // 系统状态
	PGN_BMS2_FLAUT_LEVEL = 63774, // 故障等级
	PGN_BMS2_STATE = 63774, // 各通道均衡状态
	PGN_BMS2_RESERVE_2 = 63774, // RESERVE
	PGN_BMS2_FLAUT_STATUS = 63775, // 故障状态
	
}NIU_PGN_BMS2_LIST;






// 由 ECU 数据表生成
// ECU 参数ID清单

typedef enum _niu_data_id_ecu_
{
    
	NIU_ID_ECU_BOOT_SOFT_VERSION, // BOOT软件版本
	NIU_ID_ECU_BOOT_COMPILE_TIME, // BOOT编译时间
	NIU_ID_ECU_APP_SOFT_VERSION, // APP软件版本
	NIU_ID_ECU_APP_COMPILE_TIME, // APP编译时间
	NIU_ID_ECU_HARD_VERSION, // 硬件版本号
	NIU_ID_ECU_SERIAL_NUMBER, // 生产序列号
	NIU_ID_ECU_GLOBAL_STATE, // 设备全局状态
	NIU_ID_ECU_TIMESTAMP, // 时间戳
	NIU_ID_ECU_WRITE_KEY_LEVER, // 写参数密码
	NIU_ID_ECU_BUS_KEY, // 总线通讯秘钥
	NIU_ID_ECU_BASICS_CMD, // 基础命令码
	NIU_ID_ECU_AUTH_RAND1, // RAND1
	NIU_ID_ECU_RESERVE_1, // RESERVE
	NIU_ID_ECU_AUTH_RAND2, // RAND2
	NIU_ID_ECU_AUTH_ANS1, // ANS1
	NIU_ID_ECU_AUTH_RAND3, // RAND3
	NIU_ID_ECU_AUTH_ANS2, // ANS2
	NIU_ID_ECU_AUTH_RESULT, // 鉴权结果
	NIU_ID_ECU_AUTH_FAULT_CNT, // 鉴权错误次数
	NIU_ID_ECU_BASICS_STATUES, // 基础设备状态
	NIU_ID_ECU_BASICS_ERR_STATUS, // 基础故障状态
	NIU_ID_ECU_MCU_TEMP, // 设备温度
	NIU_ID_ECU_RESERVE_2, // RESERVE
	NIU_ID_ECU_DEALER_CODE, // 经销商编码
	NIU_ID_ECU_UTC, // 时区
	NIU_ID_ECU_MOVED_LENGTH, // 异动判断距离
	NIU_ID_ECU_CAR_TYPE, // 车型编号
	NIU_ID_ECU_FAIL_VALUE, // 倾倒检测阈值
	NIU_ID_ECU_MOVE_GSENSOR_COUNT, // 检测到震动次数
	NIU_ID_ECU_MOVE_GSENSOR_TIME, // 检测时间
	NIU_ID_ECU_CAR_SPEED_INDEX, // 仪表速度系数
	NIU_ID_ECU_TIZE_SIZE, // 轮胎周长
	NIU_ID_ECU_LOST_ENERY, // 当日消耗电量wh
	NIU_ID_ECU_LOST_SOC, // 当日消耗电量
	NIU_ID_ECU_LAST_MILEAGE, // 上次骑行里程
	NIU_ID_ECU_TOTAL_MILEAGE, // 总行驶里程
	NIU_ID_ECU_SPEED_LOC_SOC, // 低电量限速开始电量
	NIU_ID_ECU_CHARGE_VALUE, // 充电开启电压
	NIU_ID_ECU_DISCHARGE_VALUE, // 结束充电电压
	NIU_ID_ECU_SHAKING_VALUE, // 震动检测阀值
	NIU_ID_ECU_OTA_BIN_URL, // 固件URL
	NIU_ID_ECU_OTA_SOFT_VER, // 固件升级软件版本
	NIU_ID_ECU_OTA_HARD_VER, // 固件升级硬件版本
	NIU_ID_ECU_OTA_PACK_SIZE, // 固件大小
	NIU_ID_ECU_OTA_RATE, // 固件升级设备进度
	NIU_ID_ECU_OTA_EXEC_EQP, // 固件升级设备
	NIU_ID_ECU_OTA_EQP, // 要升级的设备
	NIU_ID_ECU_DB_CODE_DIS_TIME, // 仪表随机码显示时间
	NIU_ID_ECU_DISPLAY_RANDOM_CODE, // 仪表显示随机码
	NIU_ID_ECU_APP_CONTROL, // 服务器控制字段
	NIU_ID_ECU_LIMITING_VELOCITY_MAX, // 进入双限速转速
	NIU_ID_ECU_LIMITING_VELOCITY_MIN, // 退出双限速转速
	NIU_ID_ECU_FRONT_TIRE_SIZE, // 前轮周长
	NIU_ID_ECU_BLE_MAC, // 蓝牙mac地址
	NIU_ID_ECU_BLE_PASSWORD, // 蓝牙密码
	NIU_ID_ECU_BLE_AES, // 蓝牙秘钥
	NIU_ID_ECU_BLE_NAME, // 蓝牙名称
	NIU_ID_ECU_SERVER_URL, // 服务器域名
	NIU_ID_ECU_SERVER_URL2, // IOT备用服务器域名
	NIU_ID_ECU_SERVER_ERROR_URL, // err上报服务器域名
	NIU_ID_ECU_SERVER_ERROR_URL2, // err上报备用服务器域名
	NIU_ID_ECU_SERVER_LBS_URL, // LBS服务器域名
	NIU_ID_ECU_SERVER_LBS_URL2, // LBS备用服务器域名
	NIU_ID_ECU_SERVER_PORT, // 服务器端口
	NIU_ID_ECU_SERVER_PORT2, // IOT备用服务器端口
	NIU_ID_ECU_SERVER_ERROR_PORT, // err上报服务器端口
	NIU_ID_ECU_SERVER_ERROR_PORT2, // err上报备用服务器端口
	NIU_ID_ECU_SERVER_LBS_PORT, // LBS服务器端口
	NIU_ID_ECU_SERVER_LBS_PORT2, // LBS备用服务器端口
	NIU_ID_ECU_ECU_KEEPALIVE, // 心跳包间隔
	NIU_ID_ECU_RESERVE_3, // RESERVE
	NIU_ID_ECU_IMEI, // IMEI
	NIU_ID_ECU_ICCID, // ICCID
	NIU_ID_ECU_IMSI, // IMSI
	NIU_ID_ECU_NO_CDMA_LOCATION, // 非cdma时基站信息
	NIU_ID_ECU_CDMA_LOCATION, // cdma时基站信息
	NIU_ID_ECU_LONGITUDE, // 经度
	NIU_ID_ECU_LATITUDE, // 纬度
	NIU_ID_ECU_AVG_LONGITUDE, // 驻车GPS平均经度
	NIU_ID_ECU_AVG_LATITUDE, // 驻车GPS平均纬度
	NIU_ID_ECU_IP, // 入网IP
	NIU_ID_ECU_HDOP, // 定位精度
	NIU_ID_ECU_PHOP, // 定位精度
	NIU_ID_ECU_HEADING, // 航向
	NIU_ID_ECU_GPS_SPEED, // GPS速度速度
	NIU_ID_ECU_GPS_MAX_CNR, // 最大GPS信号强度
	NIU_ID_ECU_GPS_MIN_CNR, // 最小GPS信号强度
	NIU_ID_ECU_GPS_AVG_CNR, // 平均GPS信号强度
	NIU_ID_ECU_GPS_SEILL_NUM, // 定位卫星数量
	NIU_ID_ECU_GPS_SLEEP_TIME, // 驻车gps休眠间隔
	NIU_ID_ECU_GPS_AWAKE_TIME, // 驻车gps唤醒时长
	NIU_ID_ECU_PITCH, // 俯仰角
	NIU_ID_ECU_ROLL, // 翻滚角
	NIU_ID_ECU_YAW, // 俯仰角
	NIU_ID_ECU_X_ACC, // X轴加速度
	NIU_ID_ECU_Y_ACC, // Y轴加速度
	NIU_ID_ECU_Z_ACC, // Z轴加速度
	NIU_ID_ECU_X_ANG, // X轴角加速度
	NIU_ID_ECU_Y_ANG, // Y轴角加速度
	NIU_ID_ECU_Z_ANG, // Z轴角加速度

	NIU_ID_ECU_MAX		// 放在最后一个
}NIU_DATA_ID_ECU;



// 由 LCU 数据表生成
// LCU 参数ID清单

typedef enum _niu_data_id_lcu_
{
    
	NIU_ID_LCU_BOOT_SOFT_VERSION, // BOOT软件版本
	NIU_ID_LCU_BOOT_COMPILE_TIME, // BOOT编译时间
	NIU_ID_LCU_APP_SOFT_VERSION, // APP软件版本
	NIU_ID_LCU_APP_COMPILE_TIME, // APP编译时间
	NIU_ID_LCU_HARD_VERSION, // 硬件版本号
	NIU_ID_LCU_SERIAL_NUMBER, // 生产序列号
	NIU_ID_LCU_GLOBAL_STATE, // 设备全局状态
	NIU_ID_LCU_TIMESTAMP, // 时间戳
	NIU_ID_LCU_WRITE_KEY_LEVER, // 写参数密码
	NIU_ID_LCU_BUS_KEY, // 总线通讯秘钥
	NIU_ID_LCU_BASICS_CMD, // 基础命令码
	NIU_ID_LCU_AUTH_RAND1, // RAND1
	NIU_ID_LCU_RESERVE_1, // RESERVE
	NIU_ID_LCU_AUTH_RAND2, // RAND2
	NIU_ID_LCU_AUTH_ANS1, // ANS1
	NIU_ID_LCU_AUTH_RAND3, // RAND3
	NIU_ID_LCU_AUTH_ANS2, // ANS2
	NIU_ID_LCU_AUTH_RESULT, // 鉴权结果
	NIU_ID_LCU_AUTH_FAULT_CNT, // 鉴权错误次数
	NIU_ID_LCU_BASICS_STATUES, // 基础设备状态
	NIU_ID_LCU_BASICS_ERR_STATUS, // 基础故障状态
	NIU_ID_LCU_MCU_TEMP, // 设备温度
	NIU_ID_LCU_STATE, // 整机状态
	NIU_ID_LCU_SWITCH_STATE, // 组合开关状态
	NIU_ID_LCU_LIGHT_STATE, // 灯具状态
	NIU_ID_LCU_X_ACC, // X轴加速度 
	NIU_ID_LCU_Y_ACC, // Y轴加速度 
	NIU_ID_LCU_Z_ACC, // Z轴加速度 
	NIU_ID_LCU_X_ANG, // X轴角加速度
	NIU_ID_LCU_Y_ANG, // Y轴角加速度
	NIU_ID_LCU_Z_ANG, // Y轴角加速度
	NIU_ID_LCU_CAR_STATE, // 车辆状态
	NIU_ID_LCU_RESERVE_2, // RESERVE
	NIU_ID_LCU_LIGHT_FAULT, // 灯光故障

	NIU_ID_LCU_MAX		// 放在最后一个
}NIU_DATA_ID_LCU;



// 由 NBC 数据表生成
// NBC 参数ID清单

typedef enum _niu_data_id_nbc_
{
    
	NIU_ID_NBC_BOOT_SOFT_VERSION, // BOOT软件版本
	NIU_ID_NBC_BOOT_COMPILE_TIME, // BOOT编译时间
	NIU_ID_NBC_APP_SOFT_VERSION, // APP软件版本
	NIU_ID_NBC_APP_COMPILE_TIME, // APP编译时间
	NIU_ID_NBC_HARD_VERSION, // 硬件版本号
	NIU_ID_NBC_SERIAL_NUMBER, // 生产序列号
	NIU_ID_NBC_GLOBAL_STATE, // 设备全局状态
	NIU_ID_NBC_TIMESTAMP, // 时间戳
	NIU_ID_NBC_WRITE_KEY_LEVER, // 写参数密码
	NIU_ID_NBC_BUS_KEY, // 总线通讯秘钥
	NIU_ID_NBC_BASICS_CMD, // 基础命令码
	NIU_ID_NBC_AUTH_RAND1, // RAND1
	NIU_ID_NBC_RESERVE_1, // RESERVE
	NIU_ID_NBC_AUTH_RAND2, // RAND2
	NIU_ID_NBC_AUTH_ANS1, // ANS1
	NIU_ID_NBC_AUTH_RAND3, // RAND3
	NIU_ID_NBC_AUTH_ANS2, // ANS2
	NIU_ID_NBC_AUTH_RESULT, // 鉴权结果
	NIU_ID_NBC_AUTH_FAULT_CNT, // 鉴权错误次数
	NIU_ID_NBC_BASICS_STATUES, // 基础设备状态
	NIU_ID_NBC_BASICS_ERR_STATUS, // 基础故障状态
	NIU_ID_NBC_MCU_TEMP, // 设备温度
	NIU_ID_NBC_RESERVE_2, // RESERVE
	NIU_ID_NBC_LIFEVALUE, // 循环心跳
	NIU_ID_NBC_WARNING, // 一级故障
	NIU_ID_NBC_FAULT, // 二级故障
	NIU_ID_NBC_POWER_STATE, // 电源工作状态
	NIU_ID_NBC_SWITCHING_SIGNAL, // 开关信号
	NIU_ID_NBC_FANS_PEED, // 风扇转速
	NIU_ID_NBC_FANS_PEED_CONTROL, // 风扇转速控制
	NIU_ID_NBC_LED_STATE, // LED状态
	NIU_ID_NBC_BATTERY_TYPE, // 充电器接入识别
	NIU_ID_NBC_MAIN_VOLTAGE1, // 输出电压1
	NIU_ID_NBC_MAIN_VOLTAGE2, // 输出电压2
	NIU_ID_NBC_MAIN_CURRENT, // 输出电流
	NIU_ID_NBC_12V_VOLTAGE, // 12V电压
	NIU_ID_NBC_MAIN_TEMPERATURE, // 温度
	NIU_ID_NBC_REFERENCE_VOLTAGE, // 参考电压
	NIU_ID_NBC_CHARGE_OVP, // 充电保护电压
	NIU_ID_NBC_CHARGE_OCP, // 充电保护电流
	NIU_ID_NBC_MAIN_VOLTAGE1_ADC, // 输出电压1AD
	NIU_ID_NBC_MAIN_VOLTAGE2_ADC, // 输出电压2AD
	NIU_ID_NBC_MAIN_CURRENT_ADC, // 输出电流AD
	NIU_ID_NBC_12V_VOLTAGE_ADC, // 12V电源AD
	NIU_ID_NBC_MAIN_VOLTAGE_CONTROL_ADC, // 电压控制AD
	NIU_ID_NBC_MAIN_CURRENT_CONTROL_ADC, // 电流控制AD
	NIU_ID_NBC_REFERENCE_TEMPERATURE_ADC, // 参考电压AD
	NIU_ID_NBC_MAIN_TEMPERATURE_ADC, // 温度采集AD
	NIU_ID_NBC_BATTERY_TYPE_ADC, // 充电接入信号AD
	NIU_ID_NBC_RESERVE_3, // 预留
	NIU_ID_NBC_CHARGE_VOLTAGE_NEED, // 充电需求电压
	NIU_ID_NBC_CHARGE_CURRENT_NEED, // 充电需求电流
	NIU_ID_NBC_CHARGE_MODE_NEED, // 充电需求模式
	NIU_ID_NBC_RESERVE_4, // 预留
	NIU_ID_NBC_FANS_CONTROL_FREQUENCY, // 风扇控制信号频率
	NIU_ID_NBC_FANS_PEED_MAX, // 风扇最大速度
	NIU_ID_NBC_RESERVE_5, // 预留
	NIU_ID_NBC_MAIN_TEMPERATURE_WARNING, // 高温警告值
	NIU_ID_NBC_MAIN_TEMPERATURE_WARNING_RECOVER, // 高温警告撤销值
	NIU_ID_NBC_MAIN_TEMPERATURE_FAULT, // 高温故障保护值
	NIU_ID_NBC_MAIN_TEMPERATURE_FAULT_RECOVER, // 高温故障撤销值
	NIU_ID_NBC_MAIN_OVP, // 电源输出过压保护
	NIU_ID_NBC_MAIN_OCP, // 电源输出过流保护
	NIU_ID_NBC_MAIN_LVP, // 电源输出低压保护
	NIU_ID_NBC_RESERVE_6, // 预留
	NIU_ID_NBC_MAIN_VOLTAGE_CONTROL_SIGNAL_RATIO, // 电压控制基准比例
	NIU_ID_NBC_MAIN_VOLTAGE_CONTROL_SIGNAL_P, // 电压基准控制P
	NIU_ID_NBC_MAIN_VOLTAGE_CONTROL_SIGNAL_I, // 电压基准控制I
	NIU_ID_NBC_MAIN_VOLTAGE_CONTROL_SIGNAL_D, // 电压基准控制D
	NIU_ID_NBC_MAIN_VOLTAGE_CONTROL_P, // 电压控制P
	NIU_ID_NBC_MAIN_VOLTAGE_CONTROL_I, // 电压控制I
	NIU_ID_NBC_MAIN_VOLTAGE_CONTROL_D, // 电压控制D
	NIU_ID_NBC_RESERVE_7, // 预留
	NIU_ID_NBC_MAIN_CURRENT_CONTROL_SIGNAL_RATIO, // 电流控制基准比例
	NIU_ID_NBC_MAIN_CURRENT_CONTROL_SIGNAL_P, // 电流基准控制P
	NIU_ID_NBC_MAIN_CURRENT_CONTROL_SIGNAL_I, // 电流基准控制I
	NIU_ID_NBC_MAIN_CURRENT_CONTROL_SIGNAL_D, // 电流基准控制D
	NIU_ID_NBC_MAIN_CURRENT_CONTROL_P, // 电流控制P
	NIU_ID_NBC_MAIN_CURRENT_CONTROL_I, // 电流控制I
	NIU_ID_NBC_MAIN_CURRENT_CONTROL_D, // 电流控制D
	NIU_ID_NBC_RESERVE_8, // 预留
	NIU_ID_NBC_MAIN_VOLTAGE1_SIGNAL_RATIO, // 输出电压1计算比例
	NIU_ID_NBC_MAIN_VOLTAGE2_SIGNAL_RATIO, // 输出电压2计算比例
	NIU_ID_NBC_MAIN_CURRENT_SIGNAL_RATIO, // 输出电流计算比例
	NIU_ID_NBC_12V_VOLTAGE_SIGNAL_RATIO, // 12V电源计算比例
	NIU_ID_NBC_CHARGE_OVP_DEVIANT, // 充电过压保护偏移值
	NIU_ID_NBC_CHARGE_OVP_RECOVER_DEVIANT, // 充电过压恢复偏移值
	NIU_ID_NBC_CHARGE_OCP_DEVIANT, // 充电过流保护偏移值
	NIU_ID_NBC_CHARGE_OCP_RECOVER_DEVIANT, // 充电过流恢复偏移值
	NIU_ID_NBC_CHARGE_LVP_DEVIANT, // 充电低压保护偏移值
	NIU_ID_NBC_CHARGE_LVP_RECOVER_DEVIANT, // 充电低压恢复偏移值
	NIU_ID_NBC_RESERVE_9, // 预留
	NIU_ID_NBC_CHARGE_DROPOUT_VOLTAGE_WARNING_DEVIANT, // 充电单节压差警告偏移值
	NIU_ID_NBC_CHARGE_DROPOUT_VOLTAGE_WARNING_RECOVER_DEVIANT, // 充电单节压差警告撤销偏移值
	NIU_ID_NBC_CHARGE_DROPOUT_VOLTAGE_FAULT_DEVIANT, // 充电单节压差保护偏移值
	NIU_ID_NBC_CHARGE_DROPOUT_VOLTAGE_FAULT_RECOVER_DEVIANT, // 充电单节压差保护撤销偏移值
	NIU_ID_NBC_CHARGE_TEMPERATURE_LOW_WARNING_DEVIANT, // 充电电池低温警告偏移值
	NIU_ID_NBC_CHARGE_TEMPERATURE_LOW_WARNING_RECOVER_DEVIANT, // 充电电池低温警告撤销偏移值
	NIU_ID_NBC_CHARGE_TEMPERATURE_LOW_FAULT_DEVIANT, // 充电电池低温保护偏移值
	NIU_ID_NBC_CHARGE_TEMPERATURE_LOW_FAULT_RECOVER_DEVIANT, // 充电电池低温保护撤销偏移值
	NIU_ID_NBC_CHARGE_TEMPERATURE_OVER_WARNING_DEVIANT, // 充电电池高温警告偏移值
	NIU_ID_NBC_CHARGE_TEMPERATURE_OVER_WARNING_RECOVER_DEVIANT, // 充电电池高温警告撤销偏移值
	NIU_ID_NBC_CHARGE_TEMPERATURE_OVER_FAULT_DEVIANT, // 充电电池高温保护偏移值
	NIU_ID_NBC_CHARGE_TEMPERATURE_OVER_FAULT_RECOVER_DEVIANT, // 充电电池高温保护撤销偏移值

	NIU_ID_NBC_MAX		// 放在最后一个
}NIU_DATA_ID_NBC;



// 由 LKU 数据表生成
// LKU 参数ID清单

typedef enum _niu_data_id_lku_
{
    
	NIU_ID_LKU_BOOT_SOFT_VERSION, // BOOT软件版本
	NIU_ID_LKU_BOOT_COMPILE_TIME, // BOOT编译时间
	NIU_ID_LKU_APP_SOFT_VERSION, // APP软件版本
	NIU_ID_LKU_APP_COMPILE_TIME, // APP编译时间
	NIU_ID_LKU_HARD_VERSION, // 硬件版本号
	NIU_ID_LKU_SERIAL_NUMBER, // 生产序列号
	NIU_ID_LKU_GLOBAL_STATE, // 设备全局状态
	NIU_ID_LKU_TIMESTAMP, // 时间戳
	NIU_ID_LKU_WRITE_KEY_LEVER, // 写参数密码
	NIU_ID_LKU_BUS_KEY, // 总线通讯秘钥
	NIU_ID_LKU_BASICS_CMD, // 基础命令码
	NIU_ID_LKU_AUTH_RAND1, // RAND1
	NIU_ID_LKU_RESERVE_1, // RESERVE
	NIU_ID_LKU_AUTH_RAND2, // RAND2
	NIU_ID_LKU_AUTH_ANS1, // ANS1
	NIU_ID_LKU_AUTH_RAND3, // RAND3
	NIU_ID_LKU_AUTH_ANS2, // ANS2
	NIU_ID_LKU_AUTH_RESULT, // 鉴权结果
	NIU_ID_LKU_AUTH_FAULT_CNT, // 鉴权错误次数
	NIU_ID_LKU_BASICS_STATUES, // 基础设备状态
	NIU_ID_LKU_BASICS_ERR_STATUS, // 基础故障状态
	NIU_ID_LKU_MCU_TEMP, // 设备温度
	NIU_ID_LKU_RESERVE_2, // RESERVE
	NIU_ID_LKU_CFG, // 配置表
	NIU_ID_LKU_STATUS, // 锁控状态
	NIU_ID_LKU_ALARM_STATE, // 报警器状态
	NIU_ID_LKU_LOCK1_STATE, // 坐垫锁状态
	NIU_ID_LKU_LOCK2_STATE, // 尾箱锁状态
	NIU_ID_LKU_LOCK3_STATE, // 龙头锁状态
	NIU_ID_LKU_HELMET_STATE, // 头盔状态
	NIU_ID_LKU_ALARM_CMD, // 报警器命令
	NIU_ID_LKU_SADDLE_CMD, // 坐垫锁命令
	NIU_ID_LKU_TAIL_BOX_CMD, // 尾箱锁命令
	NIU_ID_LKU_HEAD_KLOCK_CMD, // 龙头锁命令
	NIU_ID_LKU_BATTERY_SOC, // 内电池电量
	NIU_ID_LKU_SADDLE_CUR, // 最后一次坐垫锁电流
	NIU_ID_LKU_TAIL_BOX_CUR, // 最后一次尾箱锁电流
	NIU_ID_LKU_HEAD_LOCK_CUR, // 最后一次龙头锁电流
	NIU_ID_LKU_VLOCK_STA, // 最后一次锁供电电压
	NIU_ID_LKU_VIN_STATUS, // 外电电压
	NIU_ID_LKU_VLOCK_STATUS, // 锁供电电压
	NIU_ID_LKU_VBAT_STATUS, // 内电电压
	NIU_ID_LKU_VDD_STATUS, // MCU供电电压
	NIU_ID_LKU_SADDLE_TIMEOUT, // 坐垫锁开解锁超时时间
	NIU_ID_LKU_TAIL_BOX_TIMEOUT, // 尾箱锁开解锁超时时间
	NIU_ID_LKU_HEAD_LOCK_TIMEOUT, // 龙头锁开解锁超时时间

	NIU_ID_LKU_MAX		// 放在最后一个
}NIU_DATA_ID_LKU;

// 由 VCU 数据表生成
// VCU 参数ID清单

typedef enum _niu_data_id_vcu_
{
    
	NIU_ID_VCU_BOOT_SOFT_VERSION, // BOOT软件版本
	NIU_ID_VCU_BOOT_COMPILE_TIME, // BOOT编译时间
	NIU_ID_VCU_APP_SOFT_VERSION, // APP软件版本
	NIU_ID_VCU_APP_COMPILE_TIME, // APP编译时间
	NIU_ID_VCU_HARD_VERSION, // 硬件版本号
	NIU_ID_VCU_SERIAL_NUMBER, // 生产序列号
	NIU_ID_VCU_GLOBAL_STATE, // 设备全局状态
	NIU_ID_VCU_TIMESTAMP, // 时间戳
	NIU_ID_VCU_WRITE_KEY_LEVER, // 写参数密码
	NIU_ID_VCU_BUS_KEY, // 总线通讯秘钥
	NIU_ID_VCU_BASICS_CMD, // 基础命令码
	NIU_ID_VCU_AUTH_RAND1, // RAND1
	NIU_ID_VCU_RESERVE_1, // RESERVE
	NIU_ID_VCU_AUTH_RAND2, // RAND2
	NIU_ID_VCU_AUTH_ANS1, // ANS1
	NIU_ID_VCU_AUTH_RAND3, // RAND3
	NIU_ID_VCU_AUTH_ANS2, // ANS2
	NIU_ID_VCU_AUTH_RESULT, // 鉴权结果
	NIU_ID_VCU_AUTH_FAULT_CNT, // 鉴权错误次数
	NIU_ID_VCU_BASICS_STATUES, // 基础设备状态
	NIU_ID_VCU_BASICS_ERR_STATUS, // 基础故障状态
	NIU_ID_VCU_MCU_TEMP, // 设备温度
	NIU_ID_VCU_RESERVE_2, // RESERVE
	NIU_ID_VCU_TEMP, // 当前温度值
	NIU_ID_START_KEY_STATUS, // 一键启动状态 
	NIU_ID_VCU_SHAKE_ALARM_STATUS, // 震动报警值
	NIU_ID_VCU_DISC_POWER, // 放电功率
	NIU_ID_VCU_C_POWER, // 充电功率
	NIU_ID_VCU_PUMP_STATE, // 水泵控制状态
	NIU_ID_VCU_EBS_CONT, // EBS控制位
	NIU_ID_VCU_DCDC_CONT, // DCDC控制位
	NIU_ID_VCU_MOVE_GSENSOR_COUNT, // 检测到震动次数
	NIU_ID_VCU_PITCH, // 倾斜角度值
	NIU_ID_VCU_ROLL, // 翻滚角度值
	NIU_ID_VCU_YAW, // 仰俯角度值
	NIU_ID_VCU_RF_ID1, // 遥控器ID1
	NIU_ID_VCU_RF_ID2, // 遥控器ID2
	NIU_ID_VCU_RF_ID3, // 遥控器ID3
	NIU_ID_VCU_RF_ID4, // 遥控器ID4
	NIU_ID_VCU_LITTLE_BAT_VAL, // 小电池电压
	NIU_ID_VCU_LITTLE_BAT_STATUS, // 小电池状态
	NIU_ID_VCU_GEAR_VALUE, // 档位值
	NIU_ID_VCU_LIMIT_VELOCITY, // 限速状态

	NIU_ID_VCU_MAX		// 放在最后一个
}NIU_DATA_ID_VCU;


// 由 DB 数据表生成
// DB 参数ID清单
typedef enum _niu_data_id_db_
{
    
	NIU_ID_DB_BOOT_SOFT_VERSION, // BOOT软件版本
	NIU_ID_DB_BOOT_COMPILE_TIME, // BOOT编译时间
	NIU_ID_DB_APP_SOFT_VERSION, // APP软件版本
	NIU_ID_DB_APP_COMPILE_TIME, // APP编译时间
	NIU_ID_DB_HARD_VERSION, // 硬件版本号
	NIU_ID_DB_SERIAL_NUMBER, // 生产序列号
	NIU_ID_DB_GLOBAL_STATE, // 设备全局状态
	NIU_ID_DB_TIMESTAMP, // 时间戳
	NIU_ID_DB_WRITE_KEY_LEVER, // 写参数密码
	NIU_ID_DB_BUS_KEY, // 总线通讯秘钥
	NIU_ID_DB_BASICS_CMD, // 基础命令码
	NIU_ID_DB_AUTH_RAND1, // RAND1
	NIU_ID_DB_RESERVE_1, // RESERVE
	NIU_ID_DB_AUTH_RAND2, // RAND2
	NIU_ID_DB_AUTH_ANS1, // ANS1
	NIU_ID_DB_AUTH_RAND3, // RAND3
	NIU_ID_DB_AUTH_ANS2, // ANS2
	NIU_ID_DB_AUTH_RESULT, // 鉴权结果
	NIU_ID_DB_AUTH_FAULT_CNT, // 鉴权错误次数
	NIU_ID_DB_BASICS_STATUES, // 基础设备状态
	NIU_ID_DB_BASICS_ERR_STATUS, // 基础故障状态
	NIU_ID_DB_MCU_TEMP, // 设备温度
	NIU_ID_DB_RESERVE_2, // RESERVE
	NIU_ID_DB_STATUS, // 机车状态
	NIU_ID_DB_GEARS, // 档位
	NIU_ID_DB_SPEED, // 速度
	NIU_ID_DB_C_CUR, // 充电电流
	NIU_ID_DB_DC_CUR, // 放电电流
	NIU_ID_DB_BAT_SOC, // 电池SOC
	NIU_ID_DB_FULL_C_T, // 充电剩余时间
	NIU_ID_DB_HOUR, // 当前小时
	NIU_ID_DB_MIN, // 当前分钟
	NIU_ID_DB_F_CODE, // 故障代码
	NIU_ID_DB_BAT2_SOC, // 电池2SOC
	NIU_ID_DB_TOTAL_SOC, // 总电池SOC
	NIU_ID_DB_RGB_SET, // RGB指令
	NIU_ID_DB_STATUS2, // 车辆状态2
	NIU_ID_DB_RGB_CONFIG, // RGB配色命令
	NIU_ID_DB_MILEAGE, // 里程数

	NIU_ID_DB_MAX		// 放在最后一个
}NIU_DATA_ID_DB;


// 由 FOC 数据表生成
// FOC 参数ID清单

typedef enum _niu_data_id_foc_
{
    
	NIU_ID_FOC_BOOT_SOFT_VERSION, // BOOT软件版本
	NIU_ID_FOC_BOOT_COMPILE_TIME, // BOOT编译时间
	NIU_ID_FOC_APP_SOFT_VERSION, // APP软件版本
	NIU_ID_FOC_APP_COMPILE_TIME, // APP编译时间
	NIU_ID_FOC_HARD_VERSION, // 硬件版本号
	NIU_ID_FOC_SERIAL_NUMBER, // 生产序列号
	NIU_ID_FOC_GLOBAL_STATE, // 设备全局状态
	NIU_ID_FOC_TIMESTAMP, // 时间戳
	NIU_ID_FOC_WRITE_KEY_LEVER, // 写参数密码
	NIU_ID_FOC_BUS_KEY, // 总线通讯秘钥
	NIU_ID_FOC_BASICS_CMD, // 基础命令码
	NIU_ID_FOC_AUTH_RAND1, // RAND1
	NIU_ID_FOC_RESERVE_1, // RESERVE
	NIU_ID_FOC_AUTH_RAND2, // RAND2
	NIU_ID_FOC_AUTH_ANS1, // ANS1
	NIU_ID_FOC_AUTH_RAND3, // RAND3
	NIU_ID_FOC_AUTH_ANS2, // ANS2
	NIU_ID_FOC_AUTH_RESULT, // 鉴权结果
	NIU_ID_FOC_AUTH_FAULT_CNT, // 鉴权错误次数
	NIU_ID_FOC_BASICS_STATUES, // 基础设备状态
	NIU_ID_FOC_BASICS_ERR_STATUS, // 基础故障状态
	NIU_ID_FOC_MCU_TEMP, // 设备温度
	NIU_ID_FOC_RESERVE_2, // RESERVE
	NIU_ID_FOC_RATED_VLT, // 额定电压
	NIU_ID_FOC_MIN_VLT, // 最低电压
	NIU_ID_FOC_MAX_VLT, // 最高电压
	NIU_ID_FOC_GEARS, // 档位
	NIU_ID_FOC_RATED_CUR, // 额定电流
	NIU_ID_FOC_MOTOR_SPEED, // 电机转速
	NIU_ID_FOC_BAR_VLT, // 母线电压
	NIU_ID_FOC_BAR_CUR, // 母线电流
	NIU_ID_FOC_PHASE_CUR, // 当前相电流
	NIU_ID_FOC_TORQUE, // 电机转矩
	NIU_ID_FOC_MOTOR_TEMPERATURE, // 电机温度
	NIU_ID_FOC_COTLSTA, // FOC状态
	NIU_ID_FOC_THROTTLE_SENSOR, // 油门信号
	NIU_ID_FOC_MATCHING_MOTOR_TYTP, // 匹配电机类型
	NIU_ID_FOC_MATCHING_SPEED_SENSOR_TYTP, // 速度传感器类型
	NIU_ID_FOC_SPEED_SENSOR_ANGLE, // 速度传感器相位角
	NIU_ID_FOC_MOTOR_POLE_OF_PAIRS, // 电机及对数
	NIU_ID_FOC_GEARBOX_REDUCTION_RATIO, // 变速箱减速比
	NIU_ID_FOC_MAX_PHASE_CUR, // 最大相电流
	NIU_ID_FOC_MIN_PHASE_CUR, // 最小相电流
	NIU_ID_FOC_AVG_PHASE_CUR, // 平均电流
	NIU_ID_FOC_SET_MAX_BAR_CUR, // 最大母线电流
	NIU_ID_FOC_SET_MAX_ACCELERATING_TORQUE, // 设置加速最大转矩
	NIU_ID_FOC_SET_MAX_RETARDING_TORQUE, // 设置减速最大转矩
	NIU_ID_FOC_FOC_ACCELE, // 加速度
	NIU_ID_FOC_FOC_DCCELE, // 减速度
	NIU_ID_FOC_THROTTLE_MODE_SET, // 油门模式选择
	NIU_ID_FOC_EBS_EN, // EBS使能
	NIU_ID_FOC_EBS_RE_VLT, // EBS反充电压
	NIU_ID_FOC_EBS_RE_CUR, // EBS反充电流
	NIU_ID_FOC_BAT_SOFT_UV_EN, // 电池软欠压保护使能
	NIU_ID_FOC_BAT_SOFT_UV_VLT, // 电池软欠压电压
	NIU_ID_FOC_MOTER_RATED_SPEED, // 电机额定转速
	NIU_ID_FOC_HIGH_SPEED_RATIO, // 高档位速度比例
	NIU_ID_FOC_MID_SPEED_RATIO, // 中档位速度比例
	NIU_ID_FOC_LOW_SPEED_RATIO, // 低档位速度比例
	NIU_ID_FOC_HIGH_GER_CUR_LIMT_RATIO, // 高档位限流比例
	NIU_ID_FOC_MID_GER_CUR_LIMT_RATIO, // 中档位限流比例
	NIU_ID_FOC_LOW_GER_CUR_LIMT_RATIO, // 低档位限流比例
	NIU_ID_FOC_FLUX_WEAKEN_EN, // 弱磁使能
	NIU_ID_FOC_ENTER_FLUX_SPEED_RATIO, // 弱磁进入速度比例
	NIU_ID_FOC_EXIT_FLUX_SPEED_RATIO, // 弱磁退出速度比例
	NIU_ID_FOC_ENTER_FLUX_THROTTLE_VLT, // 弱磁进入油门电压
	NIU_ID_FOC_FLUX_W_MAX_CUR, // 弱磁最大电流
	NIU_ID_FOC_BOOST_EN, // Boost使能
	NIU_ID_FOC_BOOST_MODE, // Boost模式
	NIU_ID_FOC_BOOST_CUR, // Boost电流
	NIU_ID_FOC_BOOST_KEEP_TIME, // Boost保持时间
	NIU_ID_FOC_BOOST_INTERVAL_TIME, // Boost间隔时间
	NIU_ID_FOC_START_AUTO_EN, // 暴起模式使能
	NIU_ID_FOC_START_GEAR, // 暴起档位
	NIU_ID_FOC_START_KEEP_TIME, // 暴起持续时间

	NIU_ID_FOC_MAX		// 放在最后一个
}NIU_DATA_ID_FOC;



// 由 BMS 数据表生成
// BMS 参数ID清单

typedef enum _niu_data_id_bms_
{
    
	NIU_ID_BMS_BOOT_SOFT_VERSION, // BOOT软件版本
	NIU_ID_BMS_BOOT_COMPILE_TIME, // BOOT编译时间
	NIU_ID_BMS_APP_SOFT_VERSION, // APP软件版本
	NIU_ID_BMS_APP_COMPILE_TIME, // APP编译时间
	NIU_ID_BMS_HARD_VERSION, // 硬件版本号
	NIU_ID_BMS_SERIAL_NUMBER, // 生产序列号
	NIU_ID_BMS_GLOBAL_STATE, // 设备全局状态
	NIU_ID_BMS_TIMESTAMP, // 时间戳
	NIU_ID_BMS_WRITE_KEY_LEVER, // 写参数密码
	NIU_ID_BMS_BUS_KEY, // 总线通讯秘钥
	NIU_ID_BMS_BASICS_CMD, // 基础命令码
	NIU_ID_BMS_AUTH_RAND1, // RAND1
	NIU_ID_BMS_RESERVE_1, // RESERVE
	NIU_ID_BMS_AUTH_RAND2, // RAND2
	NIU_ID_BMS_AUTH_ANS1, // ANS1
	NIU_ID_BMS_AUTH_RAND3, // RAND3
	NIU_ID_BMS_AUTH_ANS2, // ANS2
	NIU_ID_BMS_AUTH_RESULT, // 鉴权结果
	NIU_ID_BMS_AUTH_FAULT_CNT, // 鉴权错误次数
	NIU_ID_BMS_BASICS_STATUES, // 基础设备状态
	NIU_ID_BMS_BASICS_ERR_STATUS, // 基础故障状态
	NIU_ID_BMS_MCU_TEMP, // 设备温度
	NIU_ID_BMS_LIFEVALUE, // 心跳信号
	NIU_ID_BMS_SOC, // SOC值
	NIU_ID_BMS_SOH, // SOH值
	NIU_ID_BMS_PACK_VOLTAGE, // 总电压
	NIU_ID_BMS_CURRENT, // 电流值
	NIU_ID_BMS_VOL_1, // 电压1
	NIU_ID_BMS_VOL_2, // 电压2
	NIU_ID_BMS_VOL_3, // 电压3
	NIU_ID_BMS_VOL_4, // 电压4
	NIU_ID_BMS_VOL_5, // 电压5
	NIU_ID_BMS_VOL_6, // 电压6
	NIU_ID_BMS_VOL_7, // 电压7
	NIU_ID_BMS_VOL_8, // 电压8
	NIU_ID_BMS_VOL_9, // 电压9
	NIU_ID_BMS_VOL_10, // 电压10
	NIU_ID_BMS_VOL_11, // 电压11
	NIU_ID_BMS_VOL_12, // 电压12
	NIU_ID_BMS_VOL_13, // 电压13
	NIU_ID_BMS_VOL_14, // 电压14
	NIU_ID_BMS_VOL_15, // 电压15
	NIU_ID_BMS_VOL_16, // 电压16
	NIU_ID_BMS_VOL_17, // 电压17
	NIU_ID_BMS_VOL_18, // 电压18
	NIU_ID_BMS_VOL_19, // 电压19
	NIU_ID_BMS_VOL_20, // 电压20
	NIU_ID_BMS_VOL_21, // 电压21
	NIU_ID_BMS_VOL_22, // 电压22
	NIU_ID_BMS_VOL_23, // 电压23
	NIU_ID_BMS_VOL_24, // 电压24
	NIU_ID_BMS_TEMP_1, // 电芯温度1
	NIU_ID_BMS_TEMP_2, // 电芯温度2
	NIU_ID_BMS_TEMP_3, // 电芯温度3
	NIU_ID_BMS_TEMP_4, // 电芯温度4
	NIU_ID_BMS_TEMP_5, // 电芯温度5
	NIU_ID_BMS_TEMP_6, // 电芯温度6
	NIU_ID_BMS_BALANCE_TEMP_1, // 均衡温度1
	NIU_ID_BMS_BALANCE_TEMP_2, // 均衡温度2
	NIU_ID_BMS_RECOVERY_MAX_POWER, // 最大允许回馈功率
	NIU_ID_BMS_DISCHARGE_MAX_POWER, // 最大放电功率
	NIU_ID_BMS_CHARGE_VOL, // 充电需求电压
	NIU_ID_BMS_CHARGE_CUR, // 充电需求电流
	NIU_ID_BMS_CYCLE_COUNT, // 已充电次数
	NIU_ID_BMS_CHARGINGREMAINTIME , // 充电剩余充电时间
	NIU_ID_BMS_TAPY_CAPACITY, // 额定容量
	NIU_ID_BMS_ACTUAL_CAPACITY, // 真实容量
	NIU_ID_BMS_RELAY_STATUS, // 电继电器状态
	NIU_ID_BMS_SYSTEM_STATUS, // 系统状态
	NIU_ID_BMS_FLAUT_LEVEL, // 故障等级
	NIU_ID_BMS_STATE, // 各通道均衡状态
	NIU_ID_BMS_RESERVE_2, // RESERVE
	NIU_ID_BMS_FLAUT_STATUS, // 故障状态

	NIU_ID_BMS_MAX		// 放在最后一个
}NIU_DATA_ID_BMS;



// 由 BMS2 数据表生成
// BMS2 参数ID清单

typedef enum _niu_data_id_bms2_
{
    
	NIU_ID_BMS2_BOOT_SOFT_VERSION, // BOOT软件版本
	NIU_ID_BMS2_BOOT_COMPILE_TIME, // BOOT编译时间
	NIU_ID_BMS2_APP_SOFT_VERSION, // APP软件版本
	NIU_ID_BMS2_APP_COMPILE_TIME, // APP编译时间
	NIU_ID_BMS2_HARD_VERSION, // 硬件版本号
	NIU_ID_BMS2_SERIAL_NUMBER, // 生产序列号
	NIU_ID_BMS2_GLOBAL_STATE, // 设备全局状态
	NIU_ID_BMS2_TIMESTAMP, // 时间戳
	NIU_ID_BMS2_WRITE_KEY_LEVER, // 写参数密码
	NIU_ID_BMS2_BUS_KEY, // 总线通讯秘钥
	NIU_ID_BMS2_BASICS_CMD, // 基础命令码
	NIU_ID_BMS2_AUTH_RAND1, // RAND1
	NIU_ID_BMS2_RESERVE_1, // RESERVE
	NIU_ID_BMS2_AUTH_RAND2, // RAND2
	NIU_ID_BMS2_AUTH_ANS1, // ANS1
	NIU_ID_BMS2_AUTH_RAND3, // RAND3
	NIU_ID_BMS2_AUTH_ANS2, // ANS2
	NIU_ID_BMS2_AUTH_RESULT, // 鉴权结果
	NIU_ID_BMS2_AUTH_FAULT_CNT, // 鉴权错误次数
	NIU_ID_BMS2_BASICS_STATUES, // 基础设备状态
	NIU_ID_BMS2_BASICS_ERR_STATUS, // 基础故障状态
	NIU_ID_BMS2_MCU_TEMP, // 设备温度
	NIU_ID_BMS2_LIFEVALUE, // 心跳信号
	NIU_ID_BMS2_SOC, // SOC值
	NIU_ID_BMS2_SOH, // SOH值
	NIU_ID_BMS2_PACK_VOLTAGE, // 总电压
	NIU_ID_BMS2_CURRENT, // 电流值
	NIU_ID_BMS2_VOL_1, // 电压1
	NIU_ID_BMS2_VOL_2, // 电压2
	NIU_ID_BMS2_VOL_3, // 电压3
	NIU_ID_BMS2_VOL_4, // 电压4
	NIU_ID_BMS2_VOL_5, // 电压5
	NIU_ID_BMS2_VOL_6, // 电压6
	NIU_ID_BMS2_VOL_7, // 电压7
	NIU_ID_BMS2_VOL_8, // 电压8
	NIU_ID_BMS2_VOL_9, // 电压9
	NIU_ID_BMS2_VOL_10, // 电压10
	NIU_ID_BMS2_VOL_11, // 电压11
	NIU_ID_BMS2_VOL_12, // 电压12
	NIU_ID_BMS2_VOL_13, // 电压13
	NIU_ID_BMS2_VOL_14, // 电压14
	NIU_ID_BMS2_VOL_15, // 电压15
	NIU_ID_BMS2_VOL_16, // 电压16
	NIU_ID_BMS2_VOL_17, // 电压17
	NIU_ID_BMS2_VOL_18, // 电压18
	NIU_ID_BMS2_VOL_19, // 电压19
	NIU_ID_BMS2_VOL_20, // 电压20
	NIU_ID_BMS2_VOL_21, // 电压21
	NIU_ID_BMS2_VOL_22, // 电压22
	NIU_ID_BMS2_VOL_23, // 电压23
	NIU_ID_BMS2_VOL_24, // 电压24
	NIU_ID_BMS2_TEMP_1, // 电芯温度1
	NIU_ID_BMS2_TEMP_2, // 电芯温度2
	NIU_ID_BMS2_TEMP_3, // 电芯温度3
	NIU_ID_BMS2_TEMP_4, // 电芯温度4
	NIU_ID_BMS2_TEMP_5, // 电芯温度5
	NIU_ID_BMS2_TEMP_6, // 电芯温度6
	NIU_ID_BMS2_BALANCE_TEMP_1, // 均衡温度1
	NIU_ID_BMS2_BALANCE_TEMP_2, // 均衡温度2
	NIU_ID_BMS2_RECOVERY_MAX_POWER, // 最大允许回馈功率
	NIU_ID_BMS2_DISCHARGE_MAX_POWER, // 最大放电功率
	NIU_ID_BMS2_CHARGE_VOL, // 充电需求电压
	NIU_ID_BMS2_CHARGE_CUR, // 充电需求电流
	NIU_ID_BMS2_CYCLE_COUNT, // 已充电次数
	NIU_ID_BMS2_CHARGING_REMAIN_TIME , // 充电剩余充电时间
	NIU_ID_BMS2_TAPY_CAPACITY, // 额定容量
	NIU_ID_BMS2_ACTUAL_CAPACITY, // 真实容量
	NIU_ID_BMS2_RELAY_STATUS, // 电继电器状态
	NIU_ID_BMS2_SYSTEM_STATUS, // 系统状态
	NIU_ID_BMS2_FLAUT_LEVEL, // 故障等级
	NIU_ID_BMS2_STATE, // 各通道均衡状态
	NIU_ID_BMS2_RESERVE_2, // RESERVE
	NIU_ID_BMS2_FLAUT_STATUS, // 故障状态

	NIU_ID_BMS2_MAX		// 放在最后一个
}NIU_DATA_ID_BMS2;




#ifdef __cplusplus
 {
#endif

#endif /* USER_NIU_BUS_ENUM_H_ */
