#include <assert.h>

/* widgets:
speedpowerLayer
sp_TotalContainer
sp_TotalUnitsText
sp_TotalValueText
sp_TotalTagText
sp_SignalContainer
sp_GPSSignalIcon0
sp_GPSSignalIcon1
sp_GPSSignalIcon2
sp_GPSSignalIcon3
sp_GSMSignalIcon1
sp_GSMSignalIcon2
sp_GSMSignalIcon3
sp_GSMSignalIcon0
sp_PowerValueContainer
sp_PowerUnitsText
sp_PowerValueText
sp_PowerSignedText
sp_SpeedValueContainer
sp_SpeedUnitsText
sp_SpeedValueText
sp_SpeedFrameContainer
sp_SpeedFrameNumberIcon
sp_SpeedFrameLinerIcon
sp_PowerFrameContainer
sp_PowerFrameNumberIcon
sp_PowerFrameLineIcon
*/

