#include <assert.h>

/* widgets:
bottomLayer
bottomBatContainer
bottomBatSprite
bottomDualContainer
bottomBatAFrameBackground
bottomBatABackground
bottomBatBFrameBackground
bottomBatBBackground
bottomBatBalanceTagIcon
bottomSingleContainer
bottomBatRangeTagIcon
bottomSingleFrameBackground
bottomSingleProgressBackground
bottomMieageUintsText
bottomMieagePreestimateText
bottomBatCapacityText
bottomPercentMarkText
bottomBatTagIcon
*/



