ITE SoC SDK: Configuration
Configuration
ITE DoorBell Outdoor Modules
Data Structures
struct Config
Configuration definition.
Functions
void ConfigLoad (void)
Loads configuration file.
void ConfigUpdateCrc (char *filepath)
Updates CRC files.
void ConfigSave (void)
Saves the public part of configuration to file.
void ConfigSaveAll (void)
Saves the public and private parts of configuration to file.
Variables
Config theConfig
Global instance variable of configuration.
Detailed Description
Function Documentation
void ConfigLoad (void)
Loads configuration file.
Definition at line 25 of file config.c.
References Config::area, Config::brightness, Config::building, Config::calling_time, cfgIni, cfgPrivateIni, Config::dhcp, Config::dial_time, Config::dns, Config::door_delay, Config::door_password, Config::engineer_password, Config::ext, Config::floor, Config::guard_sensor_initvalues, Config::gw, Config::help_tel, INI_FILENAME, Config::ipaddr, Config::keylevel, Config::keysound, Config::local_type, Config::mgsalarm_time, Config::netmask, Config::ringsound, Config::room, SCREENSAVER_BLANK, Config::screensaver_time, Config::screensaver_type, Config::unit, and Config::voicememo_time.
Referenced by SDL_main().
void ConfigSave (void)
Saves the public part of configuration to file.
Definition at line 221 of file config.c.
References attr, cfgIsSaving, CONFIG_SAVE, ConfigSaveTask(), and INI_FILENAME.
Referenced by ahc_echo(), and DeviceInfoInit().
void ConfigSaveAll (void)
Saves the public and private parts of configuration to file.
Definition at line 238 of file config.c.
References attr, cfgIsSaving, CONFIG_SAVE_ALL, ConfigSaveTask(), and INI_FILENAME.
Referenced by ahc_echo().
void ConfigUpdateCrc (char * filepath)
Updates CRC files.
Parameters
filepath The file path to update the CRC value. NULL for ini file on public drive.
Definition at line 203 of file config.c.
References cfgMutex, INI_FILENAME, ITP_DEVICE_NOR, ITP_IOCTL_FLUSH, and UpgradeSetFileCrc().
Referenced by LinphoneTask().
Variable Documentation
Config theConfig
Global instance variable of configuration.
Definition at line 19 of file config.c.
Referenced by ahc_echo(), CallingCall(), CallingConnectedOnCustom(), DeviceInfoInit(), DeviceInfoInitByDhcp(), LinphoneInit(), LinphonePlayKeySound(), LinphonePlayRingSound(), LinphoneSetKeyLevel(), LinphoneSetRingSound(), Parse_UCL2MEM(), ResetEthernet(), and UpgradeGetDeviceInfo().