ITE SoC SDK: Device Infomation
Device Infomation
ITE DoorBell Outdoor Modules
Maximum Administrator Unit count.
Data Structures
struct DeviceInfo
Device information definition.
Enumerations
enum DeviceType {
DEVICE_CENTER, DEVICE_OUTDOOR, DEVICE_ENTRANCE, DEVICE_BUILDING,
DEVICE_WALL, DEVICE_INDOOR, DEVICE_MANAGER, DEVICE_INDOOR2,
DEVICE_MOBILE, DEVICE_INTERCOM, DEVICE_IPCAM, DEVICE_UNKNOWN
}
Device type definition.
Functions
void DeviceInfoInit (void)
Initializes device information module.
void DeviceInfoInitByDhcp (char *ip)
Initializes device information module by DHCP setting.
Variables
DeviceInfo theCenterInfo
Device information of control server.
DeviceInfo theDeviceInfo
Device information of this device.
Detailed Description
Maximum Administrator Unit count.
Enumeration Type Documentation
enum DeviceType
Device type definition.
Enumerator
DEVICE_CENTER
Control Server.
DEVICE_OUTDOOR
Door Camera.
DEVICE_ENTRANCE
Lobby Phone.
DEVICE_BUILDING
Building Phone.
DEVICE_WALL
Wall Phone.
DEVICE_INDOOR
Indoor Phone.
DEVICE_MANAGER
Administrator Unit.
DEVICE_INDOOR2
Indoor Phone with internal SD storage.
DEVICE_MOBILE
Mobile phone.
DEVICE_INTERCOM
Intercom.
DEVICE_IPCAM
IP Camera.
DEVICE_UNKNOWN
Unknown Device.
Definition at line 34 of file doorbell.h.
Function Documentation
void DeviceInfoInit (void)
Initializes device information module.
Definition at line 10 of file device_info.c.
References AddressBookGetCenterInfo(), AddressBookGetDeviceInfo(), AddressBookGetDeviceIP(), AddressBookGetGateway(), AddressBookGetNetMask(), DeviceInfo::area, Config::area, DeviceInfo::building, Config::building, ConfigSave(), Config::dhcp, DeviceInfo::ext, Config::ext, DeviceInfo::floor, Config::floor, Config::gw, DeviceInfo::ip, Config::ipaddr, Config::local_type, Config::netmask, DeviceInfo::room, Config::room, theConfig, DeviceInfo::type, DeviceInfo::unit, and Config::unit.
Referenced by SDL_main(), and UpgradeProcessTask().
void DeviceInfoInitByDhcp (char * ip)
Initializes device information module by DHCP setting.
Parameters
ip The IP address gotten from DHCP server.
Definition at line 85 of file device_info.c.
References AddressBookGetDeviceInfo(), DeviceInfo::area, Config::area, DeviceInfo::building, Config::building, DeviceInfo::ext, Config::ext, DeviceInfo::floor, Config::floor, DeviceInfo::ip, Config::local_type, DeviceInfo::room, Config::room, theConfig, DeviceInfo::type, DeviceInfo::unit, and Config::unit.
Referenced by ResetEthernet().
Variable Documentation
DeviceInfo theCenterInfo
Device information of control server.
Definition at line 7 of file device_info.c.
Referenced by ahc_echo(), CallingCall(), EventUploadTask(), LinphoneCallDevices(), LinphoneRecordVideoMessage(), LinphoneRegister(), RemoteCheckCard(), and ResetEthernet().
DeviceInfo theDeviceInfo
Device information of this device.
Definition at line 8 of file device_info.c.
Referenced by ahc_echo(), CallingCall(), CardListCheckNumber(), EventWriteCalloutLog(), EventWriteOpenDoorLog(), EventWriteRegisterDevice(), EventWriteSnapshotLog(), LinphoneInitVideoMessageUri(), LinphoneRegister(), and RemoteCheckCard().